Update sdk and go mod vendor
hashicorp/vault pull request #10366
Opened 2020-11-09 22:28 UTC by raskchanky

2020-11-09 22:33 UTC, kalafut commented
Should we add a tag to sdk first?

2020-11-10 14:49 UTC, mladlow commented
@kalafut we haven't been and I'd rather not at this point in time, at least for this release.

2020-11-10 16:08 UTC, mladlow requested changes
Can you bundle the go version update (1.15.4) in this PR please? Verifying the go version is the first 2 steps of staging in the document. I'll update the version matrix on the wiki.

2020-11-10 18:27 UTC, calvn approved these changes

2020-11-10 18:29 UTC, mladlow approved these changes

2020-11-10 18:38 UTC, merged