Bootstrap the Consul ACL system is no token is given
hashicorp/vault pull request #10751
Opened 2021-01-24 01:39 UTC by remilapeyre

Being able to bootstrap the ACL system of Consul is something that has
long been asked of its Terraform provider (https://github.com/hashicorp/terraform-provider-consul/issues/95).

We always refused to implement a solution that would save this token in
the Terraform state has the new ACL system in 1.4 meant that we could
finally referenced some token without having access to their secret ID.
Storing the bootstrap token in the state would have made this useless
and would potentially be a security issue.

This change makes it possible to configure a new Consul secret engine
without providing a token, in that case Vault knows that the ACL system
has not yet been boostraped and do it itself. This means that will at
last be able to have completely automatic and secure Consul cluster
creation using Terraform, this has been wanted by our users for some
time now.

2022-02-02 19:44 UTC, mike-sol commented
Is there any hope for this to get merged? Would really love this functionality to be able to programmatically and idempotently bootstrap consul ACLs directly from a Terraform / Vault setup.

2022-04-09 22:19 UTC, remilapeyre commented
Hi @robmonte, conflicts should be fixed now :)

2022-04-14 17:08 UTC, robmonte requested changes
Just a couple small change requests and some additional comments. Looks great!!

2022-04-14 17:08 UTC, robmonte commented on helper/testhelpers/consul/consulhelper.go
> +		`,
Can we close this quote back on line 137?

2022-04-14 17:08 UTC, robmonte commented on website/content/docs/secrets/consul.mdx
> +1. Vault can bootstrap the ACL system of your Consul cluster if it has
Appreciate the docs update included! I think that due to the way this new feature will create the bootstrap token _and_ store it in Vault without exposing it to the user, we'll need to elaborate a bit more about this process.

I made a task for myself to add more documentation at a later date for this, but I'm happy with this current version for now!

2022-04-14 19:00 UTC, robmonte commented on builtin/logical/consul/backend_test.go
> +			testBackendConfigAccess(t, "1.3.0", false)
Can this line be updated to use version 1.3.1 to match the above test case?

2022-04-19 18:13 UTC, robmonte commented
@remilapeyre I left a PR review with some feedback and small change requests. If you have any responses to them, please let me know.

To avoid potential upcoming merge conflicts I am planning on getting this merged in very soon. If you don't have time to go through my review, I can move your commits into a new PR and make the updates myself on top of your work so you retain credit for your contribution. I'll wait a couple days before doing so.

2022-04-20 18:06 UTC, remilapeyre commented on builtin/logical/consul/path_config.go
> +}
Thanks, I updated this function :)

2022-04-20 18:07 UTC, remilapeyre commented on helper/testhelpers/consul/consulhelper.go
> +		if _, err = consul.Status().Leader(); err != nil {
Yes, when the tests run before the leader has been elected they fail on my computer, it's common enough that I needed to add this line.

2022-04-20 18:08 UTC, remilapeyre commented
Hi @robmonte, I updated the PR based on your comments. Everything should be ready now.

2022-04-20 20:30 UTC, robmonte approved these changes

2022-04-20 22:16 UTC, merged