Update index.mdx
hashicorp/vault pull request #10873
Opened 2021-02-09 19:57 UTC by lostradamus

Fixed typo in Setup section of the Secrets Engine documentation.

2021-02-09 19:57 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=10873)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=10873)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=10873).</sub>

2021-02-09 20:47 UTC, dgibbon2 requested changes
Try removing line 112

2021-02-09 20:47 UTC, dgibbon2 commented on website/content/docs/secrets/databases/index.mdx
> -   field is also be supported.
Try removing this line

2021-02-09 22:08 UTC, lostradamus commented on website/content/docs/secrets/databases/index.mdx
> -   field is also be supported.
Done!

2021-02-09 22:14 UTC, dgibbon2 approved these changes

2021-12-18 00:09 UTC, hsimon-hashicorp approved these changes

2021-12-18 00:09 UTC, merged

2021-12-18 00:10 UTC, hsimon-hashicorp commented
Thank you very much for your contribution, @lostradamus! Apologies for the delay in getting this merged.