Make cert domain name validation case insensitive
hashicorp/vault pull request #10959
Opened 2021-02-20 21:30 UTC by livyfu

This aims to address https://github.com/hashicorp/vault/issues/10852

2021-02-20 21:31 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=10959)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=10959)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=10959).</sub>

2021-02-27 05:13 UTC, thaniri approved these changes

2021-03-08 18:18 UTC, HridoyRoy requested changes

2021-03-08 18:18 UTC, HridoyRoy commented on builtin/logical/pki/cert_util.go
> +		sanitizedName := strings.ToLower(name)
Hello, 
It seems like ToLower doesn't account for non-latin characters, and IDNs can have these characters. Can we instead use EqualFold (https://golang.org/pkg/strings/#EqualFold) in the string comparison? 
Thanks!

2021-03-10 05:28 UTC, HridoyRoy approved these changes

2021-03-10 05:28 UTC, merged