Update Go to  1.16.2 for the 1.8-dev cycle
hashicorp/vault pull request #11267
Opened 2021-04-02 19:56 UTC by sgmiller

As well as SDK to 1.8-dev.

2021-04-02 20:47 UTC, raskchanky reviewed
I think you have to run `make packages` after changing `packages-oss.yml`, no?

2021-04-06 20:33 UTC, swayne275 approved these changes

2021-04-06 20:33 UTC, swayne275 commented on .circleci/config/executors/@executors.yml
> -    - image: "docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster"
did you do these manually or did it happen automatically?

i seem to remember it not happening automatically, and doing it manually broke tests for me

2021-04-06 20:33 UTC, swayne275 commented on Makefile
> -GO_VERSION_MIN=1.15.3
good find

i'm updating the doc [here](https://docs.google.com/document/d/16sjIk3hzFDPyY5A9ncxTZV_9gnpYSF1_Vx6UA1iiwgI/edit?usp=sharing) too

2021-04-06 20:48 UTC, raskchanky requested changes
Someone please correct me if I'm wrong, but I think after making changes to `packages-oss.yml`, you need to run `make packages` to update files inside `packages-oss.lock` as well as CI config. When I run `make packages` locally on this branch, there's 4 changed files that aren't included here, so I think that needs to be done before this is ready.

2021-04-07 16:46 UTC, sgmiller commented
Thanks, didn't know that.

2021-04-07 19:30 UTC, briankassouf approved these changes

2021-04-07 19:31 UTC, raskchanky approved these changes

2021-04-07 20:46 UTC, merged