Adding TLS Client CA checks to diagnose
hashicorp/vault pull request #11845
Opened 2021-06-11 19:49 UTC by hghaf099

2021-06-11 19:49 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=11845)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=11845)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=11845).</sub>

2021-06-17 16:39 UTC, HridoyRoy requested changes
A few quick formatting changes, but looking good!

2021-06-17 16:39 UTC, HridoyRoy commented on vault/diagnose/tls_verification.go
> +			return fmt.Errorf("'tls_disable_client_certs' and 'tls_require_and_verify_client_cert' are mutually exclusive")
```suggestion
			return fmt.Errorf("the tls_disable_client_certs and tls_require_and_verify_client_cert fields in the listener stanza of the vault server config are mutually exclusive fields. Please ensure they are not both set to true.")
```

2021-06-17 16:39 UTC, HridoyRoy commented on command/operator_diagnose.go
> +				fmt.Println("Checking TLS cleint CA file check and the error is : ", err)
Let's remove these print statements.

2021-06-17 16:39 UTC, HridoyRoy commented on vault/diagnose/tls_verification.go
> +func TLSMutualExclusionCertCheck(l *configutil.Listener) error {
This function needs to be called in `operator_diagnose`.

2021-06-17 16:39 UTC, HridoyRoy commented on vault/diagnose/tls_verification.go
> +	data, err := ioutil.ReadFile(l.TLSClientCAFile)
This works, but I think for the sake of reusing code, we should use https://github.com/hashicorp/vault/blob/13629ca2d4e8ddd221086751d9a09d75bd46cf49/vault/diagnose/tls_verification.go#L97

2021-06-17 16:39 UTC, HridoyRoy commented on vault/diagnose/tls_verification_test.go
> +func TestTLSValidClientCAFile(t *testing.T) {
Could we add comments to these tests?

2021-06-17 16:39 UTC, HridoyRoy commented on internalshared/listenerutil/listener.go
> +		// TODO: Wouldn't we have to provide the TLSClientCAFile if TLSRequireAndVerifyClientCert is set?
Can we remove this comment and track investigation for this in a jira? Thanks!

2021-06-17 16:40 UTC, HridoyRoy commented on vault/diagnose/tls_verification.go
> +	// TODO: should we run the CA cert through the TLSFileChecks function as well?
Yep, I'd like to add that to this PR if you don't mind?

2021-06-18 12:58 UTC, hghaf099 commented
This PR is old, and I will just close it. I have addressed the comments in https://github.com/hashicorp/vault/pull/11860/

2021-06-18 12:58 UTC, closed without merging