Checking Validity of all Certs in the chain
hashicorp/vault pull request #11883
Opened 2021-06-17 13:19 UTC by hghaf099

2021-06-17 14:07 UTC, hghaf099 commented on vault/diagnose/tls_verification.go
> +	rootSubjects := GetCertsSubjects(rootCerts)
I am not sure if this is needed or not! For self-signed certs, the cert can verify itself, and the subject and issuer are the same. So, just checking if we have subjects is not enough to determine if the cert is a self-signed cert. So, maybe we can just check if  "len(rootCerts) == 0".

2021-06-17 16:03 UTC, HridoyRoy requested changes
Looking very good so far! Just a few small changes and then it's good to go!

2021-06-17 16:03 UTC, HridoyRoy commented on vault/diagnose/tls_verification.go
> +		warnings = append(warnings, fmt.Sprintf("LeafCerts contains more than one leafCert."))
```suggestion
		warnings = append(warnings, fmt.Sprintf("More than one leaf certificate detected. Please ensure that there is one unique leaf certificate being supplied to vault in the vault server config file."))
```

2021-06-17 16:03 UTC, HridoyRoy commented on vault/diagnose/tls_verification_test.go
> -	if warnings == nil || len(warnings) != 1 {
Can you add a check for the other warning thrown in this test to ensure it is expected?

2021-06-17 16:03 UTC, HridoyRoy commented on vault/diagnose/tls_verification_test.go
>  // TestTLSMultiCerts verifies that a unique error message is thrown when a cert is specified twice.
```suggestion
// TestTLSCertAsKey verifies that a unique error message is thrown when a cert is specified twice.
```

2021-06-17 16:03 UTC, HridoyRoy commented on vault/diagnose/tls_verification_test.go
> +	if errs != nil {
Could you do an explicit check here to make sure the right error is returned for this test?

2021-06-17 16:05 UTC, HridoyRoy commented
Seems like `test-go` checks are failing due to the new code. Could you update those tests to reflect the code changes you've made?

2021-06-17 22:55 UTC, hghaf099 commented on vault/diagnose/tls_verification_test.go
> +	_, err := tls.LoadX509KeyPair("./../../api/test-fixtures/keys/cert.pem", "./test-fixtures/ecdsa.key")
The ListenerChecks returns with error before it tls.LoadX509KeyPair in TLSFileChecks

2021-06-17 22:56 UTC, hghaf099 commented on vault/diagnose/tls_verification_test.go
> +func TestTLSSelfSignedCert(t *testing.T) {
I should have removed this test, I will add that to the other PR

2021-06-17 23:04 UTC, hghaf099 commented on vault/diagnose/tls_verification.go
> +	for i, lc := range certs {
did not get what needs to be done here? should I change the naming for "lc"? :)

2021-06-18 15:59 UTC, HridoyRoy commented on vault/diagnose/tls_verification.go
> +	for i, lc := range certs {
Sorry about the confusion! I meant to say, let's change the name `lc` to `leafCert`

2021-06-18 22:44 UTC, HridoyRoy approved these changes
Looks good, nice work!

2021-06-22 20:23 UTC, HridoyRoy approved these changes

2021-06-22 20:23 UTC, merged