Adding support for SHA3 in the transit backend.
hashicorp/vault pull request #12150
Opened 2021-07-22 18:12 UTC by robison

This PR is intended to add support for SHA3 as a hashing algorithm in the `transit` backend. Feedback most appreciated!

2021-11-10 14:01 UTC, victorr commented
Hello @robison!

I'm going to review your PR, but would you mind rebasing it in the meanwhile?

Kind regards.

2021-11-15 22:14 UTC, victorr requested changes
The PR looks good to me. Once the unit tests for sign and verify are added the PR will be ready to merge. 

Thank you for the work you have already put into this PR!

2021-11-15 22:14 UTC, victorr commented on vault/logical_system.go
> +	case "sha3-224":
What about updating the documentation for this operation in `vault/logical_system_paths.go`?

2021-12-08 18:29 UTC, closed without merging

2021-12-08 18:34 UTC, schultz-is commented
Howdy @robison. Just wanted to let you know that we brought this functionality in with #13367, which includes your commit. Thanks for your contribution!