add known issue for dr secondary lease count quota invalidation
hashicorp/vault pull request #12288
Opened 2021-08-09 18:15 UTC by swayne275

Note: DR Secondaries are for ent, but since this is for docs (not in ent-specific files) I figured OSS is the best place for them. I scanned the wiki page and didn't see any clarifying info - either I missed it, or that might be a good update to make!

2021-08-09 18:20 UTC, vishalnayak approved these changes

2021-08-09 18:23 UTC, mladlow commented
It might take me a little while to review this but I'd like to request changes, so if you could hold off on merging, that would be helpful.

2021-08-09 19:45 UTC, mladlow requested changes
I think it would be more consistent and more obvious to put the "known issues" on the 1.6.0 and 1.7.0 upgrade pages, as there isn't a known issue with 1.6.6 or 1.7.4. Changing that would mean that you don't need to add a new page for 1.6.6 and 1.7.4.

2021-08-09 19:45 UTC, mladlow commented on website/content/partials/lease-count-quota-upgrade.mdx
> +a hard shutdown. This issue exists prior to Vault 1.6.6, and 1.7.4. It has been
```suggestion
a hard shutdown. This issue exists prior to Vault 1.6.6, and 1.7.4. It is
```

2021-08-09 19:45 UTC, mladlow commented on website/content/partials/lease-count-quota-upgrade.mdx
> +a hard shutdown. This issue exists prior to Vault 1.6.6, and 1.7.4. It has been
It won't quite be released when this PR merges, so we can leave the tense ambiguous this way.

2021-08-09 19:45 UTC, mladlow commented on website/content/docs/upgrading/upgrade-to-1.7.4.mdx
> +page_title: Upgrading to Vault 1.7.4 - Guides
Like the 1.6.6 upgrade page, we should put this on the 1.7.0 upgrade page at least, and maybe 1.7.1/1.7.2/1.7.3 (but I'm more on the fence about those).

2021-08-09 19:45 UTC, mladlow commented on website/data/docs-nav-data.json
> +      {
If we get rid of the 1.6.6 and 1.7.4 pages, we won't want these links.

2021-08-09 21:22 UTC, swayne275 commented
@mladlow I resolved your comments (thanks!). Let me know if you'd like this info to also be put on the minor 1.6 and 1.7 pages

2021-08-10 18:49 UTC, mladlow approved these changes
I think we don't need to add it to the other pages.

2021-08-23 21:58 UTC, merged