UI/pki cert parse
hashicorp/vault pull request #12541
Opened 2021-09-13 19:14 UTC by hellobontempo

2021-09-20 15:59 UTC, hellobontempo commented on ui/app/templates/components/pki-cert-show.hbs
> +      {{else if (and (get model attr.name) (or (eq attr.name "issueDate") (eq attr.name "expiryDate")))}}
Only pass to date-format helper if `get model attr.name` returns a value AND `attr.name` equals `issueDate` or `expiryDate`

2021-09-20 16:02 UTC, hellobontempo commented on ui/app/templates/components/config-pki-ca.hbs
> +      {{else if (and (get model attr.name) (or (eq attr.name "issueDate") (eq attr.name "expiryDate")))}}
Only pass to date-format helper if `get model attr.name` returns a value AND `attr.name` equals `issueDate` or `expiryDate`

2021-09-21 19:16 UTC, Monkeychip commented on ui/app/models/pki-ca-certificate.js
> +  expiryDate: attr('string', {
not as long as you update it wherever it's been called.

2021-09-21 19:18 UTC, Monkeychip approved these changes
This looks great! nice work.

2021-09-22 01:56 UTC, light1021 commented
> Thanks for the suggestion, @light1021! We definitely see this is a useful addition and I believe it's going to be addressed in another PR. I'll check-in with our design team to make sure this is the case.

Any way, thanks for your work~

2021-09-27 18:38 UTC, hashishaw requested changes
Very nice work! A couple small updates requested

2021-09-27 18:38 UTC, hashishaw commented on ui/app/adapters/pki-ca-certificate.js
>        store.pushPayload(type.modelName, response);
We don't need this line, since it is handled in the `else` block

2021-09-27 18:38 UTC, hashishaw commented on ui/app/helpers/parse-pki-cert.js
> +  const certMetadata = {
small nit: you can just return this object as defined, so 
```
return {
  common_name: commonName,
  ...
}
```

2021-09-27 18:38 UTC, hashishaw commented on ui/app/models/pki-ca-certificate.js
> +  // NOTE: attr was previously "expiration" not sure if changing to expiryDate breaks everything
Probably don't want to leave this note in here :)

2021-09-27 18:38 UTC, hashishaw commented on ui/app/models/pki-certificate.js
> +    // check here for ordering
remove comment

2021-09-27 18:38 UTC, hashishaw commented on ui/app/templates/components/config-pki-ca.hbs
> +        <InfoTableRow data-test-table-row={{value}}
👏

2021-09-27 18:38 UTC, hashishaw commented on ui/lib/core/addon/helpers/date-format.js
> +  if (isFormatted) {
Can we add a scenario to this helper's test file to cover this behavior?

2021-09-27 20:07 UTC, hellobontempo commented on ui/app/models/pki-certificate.js
> +    // check here for ordering
woop! thank you

2021-09-28 15:04 UTC, hashishaw approved these changes
🚀

2021-10-04 21:31 UTC, merged

2021-10-07 19:47 UTC, hellobontempo commented
> @hellobontempo will there need to be documentation updates for this change?

@mladlow - Thanks for checking! Nope - I don't think so. The only relevant docs I see are [Build Your Own Certificate Authority (CA)](https://learn.hashicorp.com/tutorials/vault/pki-engine) and I don't seen any screenshots that display the certificate data. This PR is just visual and adds some of the cert metadata to the certificate view page.