Update production hardening guidelines
hashicorp/vault pull request #12585
Opened 2021-09-20 16:41 UTC by mickael-hc

Quick update to the production guidelines based on a previous audit

2021-09-21 17:52 UTC, chair6 requested changes
These look like useful additions.. just a couple small suggestions to address typos.

2021-09-21 17:52 UTC, chair6 commented on website/content/guides/operations/production.mdx
> +- **Use Safest Algoritms Available**. Vault supports a variety of legacy algorithms
```suggestion
- **Use Safest Algorithms Available**. Vault supports a variety of legacy algorithms
```

2021-09-21 17:52 UTC, chair6 commented on website/content/guides/operations/production.mdx
> +  recommended for use, especially if a stronger alternative is available.
```suggestion
  be recommended for use, especially if a stronger alternative is available.
```

2021-09-23 15:40 UTC, ncabatoff approved these changes

2021-09-23 15:42 UTC, chair6 approved these changes

2021-09-23 18:37 UTC, merged