auth/kubernetes: add changelog for issuer deprecation
hashicorp/vault pull request #13126
Opened 2021-11-11 20:25 UTC by imthaghost

This adds a missing changelog in 1.9 for Kubernetes auth issuer deprecation: hashicorp/vault-plugin-auth-kubernetes#127.

The plugin was updated in the PR to Vault: #12975.

2021-11-11 22:58 UTC, mladlow requested changes
Thanks for adding this! If this PR merges to main this note will appear in the 1.10 CL, but not the 1.9 CL. If we'd like this to appear in the 1.9 CL, this PR needs to merge to the 1.9 release branch _only_, and not the main branch.

2021-11-11 23:10 UTC, tvoran commented on changelog/13126.txt
> +auth/kubernetes: `disable_iss_validation` and `issuer` configuration fields deprecation  [#127](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/127)
Just a thought on wording:

```suggestion
auth/kubernetes: deprecate `disable_iss_validation` and `issuer` configuration fields [#127](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/127)
```

2021-11-11 23:10 UTC, tvoran commented on changelog/13126.txt
> +```
I'm thinking this should have a `change` entry too, in the same file, something like:

````
```release-note:change
auth/kubernetes: default `disable_iss_validation` to true [[GH-127](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/127)]
``` 
````

2021-11-17 15:58 UTC, mladlow commented
Since this hasn't merged, and we've staged the release, we should plan to make changelog updates directly on the changelog itself. I'm happy to chat through the whys of that in more depth.

2021-11-18 18:37 UTC, closed without merging