recognize ed25519 key type and return PKCS8 format
hashicorp/vault pull request #13257
Opened 2021-11-23 19:11 UTC by navaneethrameshan

Addresses #13256

convertRespToPKCS8 does not recognize the ed25519 key. Changes
to recognize ed25519 key and return its PKCS8 format

2021-11-23 19:14 UTC, navaneethrameshan commented
Requires #13254 to verify and validate this PR

2021-11-24 18:33 UTC, stevendpclark requested changes
Great stuff, much appreciated @navaneethrameshan for the second fix in this area!

Could I ask that you rename the changelog file adding a .txt to the filename please?

2021-11-24 18:48 UTC, stevendpclark approved these changes

2021-11-24 18:48 UTC, navaneethrameshan commented
Thank you @stevendpclark! Updated the changelog file name.

2021-11-24 19:24 UTC, merged