Allow specifying multiple allowed SSH key lengths
hashicorp/vault pull request #13991
Opened 2022-02-09 21:38 UTC by cipherboy

In the ssh secrets engine, only a single allowed key length was allowed
for each algorithm type. However, many algorithms have multiple safe
values (such as RSA and ECDSA); allowing a single role to have multiple
values for a single algorithm is thus helpful.

On creation or update, roles can now specify multiple types using a list
or comma separated string of allowed values:

    allowed_user_key_lengths: map[string][]int{"rsa": []int{2048, 4096}}

`Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>`

2022-02-10 16:20 UTC, stevendpclark approved these changes

2022-02-10 18:05 UTC, sgmiller requested changes

2022-02-14 18:12 UTC, cipherboy commented on website/content/api-docs/secret/ssh.mdx
> +- `allowed_user_key_lengths` `(map<string|int|[]int>: "")` – Specifies a map of ssh key types
Should this type signature be `map<string|(int|[]int)>` instead perhaps? Not really sure how to indicate an optional list of int-like types.

2022-02-17 19:14 UTC, stevendpclark approved these changes

2022-02-17 19:14 UTC, stevendpclark commented on builtin/logical/ssh/path_sign.go
> +				case "rsa":
Technically correct, but we are now incongruent on the key names we accept for "key types" from PR#14008 and what the names/values we allow for this key. Not the end of the world just pointing it out.

2022-02-17 20:36 UTC, cipherboy commented
Thanks all!

2022-02-17 20:36 UTC, merged