Allow generation of other types of SSH CA keys
hashicorp/vault pull request #14008
Opened 2022-02-10 21:13 UTC by cipherboy

Curious about general sentiment here; if it is positive, I'll add docs and a changelog and we can decide what to do about the UI (leave it as-is or drop it for future work).

See https://github.com/hashicorp/vault/issues/11035 for context. We derive types from the `x/crypto/ssh` types (which match OpenSSH's constants), thus making key bits only relevant for RSA keys. We're notably short exporting the private key (for parity with PKI secrets engine).

---

This probably needs some additional UI work, but it works :laughing:

@ivana-mcconnell or @hellobontempo do either you have any thoughts here? It seems like the UI of SSH CA generation isn't at all like the PKI functionality; it looks like there's no dynamic fields (the hbs template needed to be updated manually) and lacks a lot of the actions for groups &c. I couldn't figure out how to use a `<Select />` component either; it appears to require an `onChange` action (which we appear to lack completely) and even without it, the `options` didn't populate (either manually or from the element's chosen values). Similarly failed via `<FormFieldFromModel />` -- that didn't even display at all. :/

2022-02-11 13:50 UTC, stevendpclark commented on builtin/logical/ssh/path_config_ca_test.go
> +	// Successfully create a new RSA/2048 one
Could you convert this to a table driven test to cut down on the overall code and make it clearer in the future if a test fails which algo is causing us issues?

2022-02-11 13:51 UTC, stevendpclark commented on builtin/logical/ssh/path_config_ca.go
> +	var publicKey interface{}
```suggestion
	var publicKey crypto.PublicKey
```

2022-02-11 13:53 UTC, stevendpclark commented on builtin/logical/ssh/path_config_ca.go
> +		publicKey = &privateSeed.PublicKey
I'd rather us use the Public() method on the crypto algos as they behave a little differently across the various implementations :(

```suggestion
		publicKey = privateSeed.Public()
```

2022-02-11 13:54 UTC, stevendpclark commented on builtin/logical/ssh/path_config_ca.go
> +		publicKey = &privateSeed.PublicKey
```suggestion
		publicKey = privateSeed.Public()
```

2022-02-11 13:58 UTC, stevendpclark reviewed
Overall +1 from me, a few little nits on the specific PR and I'll let others discuss/decide about the UI parts of this PR, hence the lack of approval from my part.

2022-02-14 13:54 UTC, sgmiller requested changes
Looks good to me.  Needs docs and changelog though.

2022-02-14 19:13 UTC, ivana-mcconnell commented
@cipherboy Thanks! Just wanting to make sure I understand the desired behaviour here: we want to enable a user to select the key type first (from ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, or ssh-ed25519) and then, based on that, enter the key bits. Is that correct? 

Should key bits be an open input, or are there only specific values that are allowed for each key type?

2022-02-14 19:28 UTC, cipherboy commented
Hey @ivana-mcconnell!

I'd actually love to see something similar to those boxes in the PKI UI RFC doc where the user first selects if they're going to import a SSH CA (first two fields on that form) OR if they're going to generate a key. (Or put them under folding menus, you'd know better than me!).

In the former case, they just need the top two fields (private/public key).

In the latter case, they just need the two new fields. Yes, ideally a drop-down would be best for the key type; I tried getting that working with a select but failed. Presently key bits is only necessary when `keyType == ssh-rsa` so yes, could definitely be hidden otherwise :-) For now, its the standard RSA key sizes (which would either be an int or if you wanted some sane limits, values of 2048, 3072, 4096, and _maybe_ something larger but unlikely). Lemme know if you think there's some easy fixes I could do (and some existing code that does it right) or what :-)

2022-02-14 20:03 UTC, hellobontempo commented
> Hey @ivana-mcconnell!
> 
> I'd actually love to see something similar to those boxes in the PKI UI RFC doc where the user first selects if they're going to import a SSH CA (first two fields on that form) OR if they're going to generate a key. (Or put them under folding menus, you'd know better than me!).
> 
> In the former case, they just need the top two fields (private/public key).
> 
> In the latter case, they just need the two new fields. Yes, ideally a drop-down would be best for the key type; I tried getting that working with a select but failed. Presently key bits is only necessary when `keyType == ssh-rsa` so yes, could definitely be hidden otherwise :-) For now, its the standard RSA key sizes (which would either be an int or if you wanted some sane limits, values of 2048, 3072, 4096, and _maybe_ something larger but unlikely). Lemme know if you think there's some easy fixes I could do (and some existing code that does it right) or what :-)

Once design (@ivana-mcconnell) has put together designs for this I'm happy to review your PR, or pair through implementing in the UI

2022-02-14 20:07 UTC, cipherboy commented on builtin/logical/ssh/path_config_ca.go
> +				Description: `Specifies the desired key type when generating; must be ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, or ssh-ed25519.`,
Should accept all forms (rsa, ec, ssh-rsa, &c).

2022-02-14 21:02 UTC, cipherboy commented
fmt errors all in unrelated files.

Per discussion with @ivana-mcconnell, removed the fledgling UI :-)

2022-02-15 14:18 UTC, stevendpclark approved these changes

2022-02-15 18:59 UTC, sgmiller approved these changes

2022-02-15 19:14 UTC, merged