Documentation changes in /sys/managed-keys
hashicorp/vault pull request #14377
Opened 2022-03-04 17:35 UTC by divyapola5

With the testing done as part of VAULT-4246, it was noticed that /sys/managed-keys documentation needs some updates.
This PR addresses those changes. See VAULT-5320 for more details.

2022-03-04 17:50 UTC, sgmiller requested changes

2022-03-04 17:50 UTC, sgmiller commented on website/content/api-docs/system/managed-keys.mdx
> +- `type` `(string: <required>)` – The backend type for the managed key. Supported options are `pkcs11` and `awskms`.
and 'azurekeyvault`

2022-03-14 17:38 UTC, divyapola5 commented on website/content/api-docs/system/managed-keys.mdx
> +- `type` `(string: <required>)` – The backend type for the managed key. Supported options are `pkcs11` and `awskms`.
done

2022-03-14 20:16 UTC, victorr commented on website/content/api-docs/system/managed-keys.mdx
> +- `type` `(string: "awskms")` - To select an AWS KMS backend, the type parameter must be set to `awskms`
Missing a period to end the sentence.

2022-03-14 20:16 UTC, victorr commented on website/content/api-docs/system/managed-keys.mdx
> +- `type` `(string: "azurekeyvault")` - To select an Azure Key Vault backend, the type parameter must be set to `azurekeyvault`
Missing a period to end the sentence.

2022-03-14 20:23 UTC, divyapola5 commented on website/content/api-docs/system/managed-keys.mdx
> +- `type` `(string: "azurekeyvault")` - To select an Azure Key Vault backend, the type parameter must be set to `azurekeyvault`
Thanks. Updated the code.

2022-03-14 20:24 UTC, victorr approved these changes
👍

2022-03-18 19:50 UTC, sgmiller approved these changes

2022-03-18 19:51 UTC, merged