builtin/logical/transit: fix clobbered err
hashicorp/vault pull request #14733
Opened 2022-03-28 14:13 UTC by alrs

This fixes an `err` variable passed into a test function but left unused.

2022-03-29 22:28 UTC, alrs commented
If I could, I'd add the `no-changelog` label.

2022-04-01 16:38 UTC, stevendpclark requested changes
Hi @alrs, 

Thanks for the PR submission! I have a minor comment on the fix that you propose, let me know your thoughts.

2022-04-01 16:38 UTC, stevendpclark commented on builtin/logical/transit/stepwise_test.go
> +			if err != nil {
While I agree, this is probably the fix that makes the most sense, this test is now incongruent with all the other tests that we ignore the passed in error into the Assert function. 

Could we instead rename the err variable on line 208 or apply this fix to all the other tests within this file?

2024-06-26 15:46 UTC, stevendpclark commented
As this PR is fairly old now with no feedback on the requested changes, I'll close it out. 

Please feel free to re-open the PR if you feel strongly about the fix.

2024-06-26 15:46 UTC, closed without merging