Add unauthed JSON fetching of CRLs, Issuers
hashicorp/vault pull request #15253
Opened 2022-05-02 14:34 UTC by cipherboy

We make the `GET /issuer/:issuer_ref/crl` endpoint return the JSON-wrapped CRL now, with `/pem` and `/der` being required suffixes for "bare" fetches.

We similarly add a `GET /issuer/:issuer_ref/json` endpoint for the JSON-wrapped issuer certificate _without_ the extra data of `GET /issuer/:issuer_ref` (chain information, &c).

Lastly, we make the various fetch endpoints unauthenticated, allowing arbitrary systems to list, fetch the issuer's certs and corresponding CRLs.

Since this is a new endpoint, I figured it was time to put the CRL in a field named `crl` rather than `certificate`. :-)

2022-05-02 15:39 UTC, sgmiller requested changes
Do we want to add a quick unit test for the new JSON returns?

2022-05-02 16:37 UTC, cipherboy commented
@sgmiller Updated.

2022-05-02 16:43 UTC, sgmiller approved these changes
Thanks!

2022-05-02 20:50 UTC, stevendpclark commented on builtin/logical/pki/backend_test.go
> +	path := fmt.Sprintf("/v1/%v/issuer/%v/crl/der", mountPoint, issuer)
Curious why did this path change? If we needed to add a der to it that would mean we aren't backwards compat anymore?

2022-05-02 20:54 UTC, stevendpclark approved these changes

2022-05-03 12:41 UTC, cipherboy commented
Thanks all! Manually merged.

2022-05-03 12:41 UTC, closed without merging

2022-06-20 15:55 UTC, cipherboy commented
This PR was merged in #15277. See that PR and the relevant docs PR #15238 for more information about this change.