Vault-5619
hashicorp/vault pull request #15582
Opened 2022-05-24 20:48 UTC by rculpepper

2022-05-24 21:03 UTC, sgmiller requested changes
Just a couple notes.

2022-05-24 21:03 UTC, sgmiller commented on website/content/docs/secrets/transit.mdx
> +## BYOK
Lets be explicit here: "Bring Your Own Key (BYOK)"

2022-05-24 21:03 UTC, sgmiller commented on website/content/docs/secrets/transit.mdx
> +## BYOK
Also, I'd like some language discouraging BYOK when not needed.  Something like "While creating a key within the Transit Secrets Engine and letting Vault create and manage the key material is more secure, there may be a need to bring a key from an existing HSM or system.  The key import functionality enables this case."

2022-05-26 16:14 UTC, cipherboy requested changes

2022-05-26 16:14 UTC, cipherboy commented on website/content/docs/secrets/transit.mdx
> +be generated and then used to wrap the target key using the CKM_AES_KEY_WRAP_PAD mechanism.
Just a note, this mechanism is wrong. Per the [updated PKCS#11 v3.0 spec](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc370634387) and the Transit implementation, this should be `CKM_AES_KEY_WRAP_KWP`.

2022-06-06 18:15 UTC, closed without merging