MFA: TOTP: Add a non-administrative destory call, use non-administrative calls in the UI
hashicorp/vault pull request #16504
Opened 2022-07-29 08:41 UTC by the-glu

Hello,

The UI to setup MFA with TOTP is using administrative calls, which can be can issue since entities with restricted rights must have permission to call those endpoints, allowing then to add or remove TOTP to any entity.

This PR change the UI to use the non-administrative endpoints who can be granted to anyone since they does not pose a security risk.

Since the 'destroy' endpoint exists only in a administrative version, this PR also add a new non-administrative endpoint, like the 'generate' endpoint.

2022-07-29 08:42 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=16504)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=16504)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=16504).</sub>

2022-08-25 19:41 UTC, the-glu commented
Hello,

Any feedback for this PR? It would be great to have this feature :)

Thanks,

2023-02-08 10:43 UTC, alexleach commented
I too was looking to allow a non-administrative user to generate their own TOTP method using the UI, so would like to see this included 😄 

Having just had a browse through the file changes, should the `default` policy also grant access to the `identity/mfa/method/totp/generate` and `identity/mfa/method/totp/destroy` endpoints? e.g.

```
# Allow a user to generate their own TOTP QR code / method
path "identity/mfa/method/totp/generate" {
  capabilities = ["create", "update"]
}

# Allow a user to destroy their own TOTP method
path "identity/mfa/method/totp/destroy" {
  capabilities = ["create", "update"]
}
```

Otherwise, I think there should be documentation about the required user policy permissions somewhere.

I've also noticed a typo on the [totp.mdc documentation page](https://github.com/hashicorp/vault/pull/16504/files#diff-34c0c8632f156ff19c031198519989bc1976d207fc2e169df7806cbaa4951fb1). Line 178 doesn't need `my_totp/` in the URL. I'll add a comment on it.

2023-02-08 10:50 UTC, alexleach commented on website/content/api-docs/system/mfa/totp.mdx
> +    http://127.0.0.1:8200/v1/sys/mfa/method/totp/my_totp/destroy
`my_totp/` isn't required in the URL here, as the `:name` parameter is actually `totp` in this Sample Request.

2023-02-08 10:57 UTC, alexleach commented on vault/login_mfa.go
> +func (i *IdentityStore) handleLoginMFADestroyCommon(ctx context.Context, req *logical.Request, methodID, entityID string) (*logical.Response, error) {
Should the `methodID` argument should be defined as a `string`?

2023-03-06 12:59 UTC, oyvsi commented
non-administrative calls in the UI was added in https://github.com/hashicorp/vault/pull/17932, but non-administrative destroy is still missing.

2023-04-17 21:01 UTC, hsimon-hashicorp commented
Hi folks - we are discussing this internally with our engineering teams and product owners. I apologize for the delay and want to say that we appreciate your patience. :)

2023-10-31 22:13 UTC, schavis requested changes

2023-10-31 22:13 UTC, schavis commented on website/content/api-docs/system/mfa/totp.mdx
> +This endpoint deletes a TOTP MFA secret in the entity of the calling token.
```suggestion
Delete a TOTP MFA secret in the entity of the calling token.
```
Style correction: avoid "this" as a pronoun

2023-10-31 22:13 UTC, schavis commented on website/content/api-docs/system/mfa/totp.mdx
> +secret.
```suggestion
<Warning title="You cannot overwrite entity secrets">

To change a secret on the entity, you must explicity delete the secret with the
Destroy endpoint then create a new secret with the `generate` or
`admin-generate` endpoints.

</Warning>
```

Style correction: write in the active voice

2024-05-14 20:08 UTC, Monkeychip commented
I'm going to close this PR, as it looks like this was addressed in #17932.

2024-05-14 20:08 UTC, closed without merging