Enable Iron Bank integration
hashicorp/vault pull request #17482
Opened 2022-10-10 18:21 UTC by marianoasselborn

Enables Iron Bank updates after linux artifacts are published.

2022-10-10 18:34 UTC, alvin-huang approved these changes

2022-10-10 18:35 UTC, alvin-huang requested changes
Actually we can't trigger it like this right now, there can't be two events dependent on one job it has to be serial.

2022-10-10 22:04 UTC, alvin-huang approved these changes

2022-10-11 09:40 UTC, samsalisbury approved these changes

2022-10-11 14:25 UTC, merged