UI: OIDC callback bug.
hashicorp/vault pull request #18138
Opened 2022-11-29 15:18 UTC by DavidSpek

When implementing vault with our OIDC provider, the popup window never closes and the OIDC callback never succeeds. This is because the main window is listening for message events from the popup window. However, in our OIDC consent page other message events originating from Intercom are sent and these break the callback handling. This is because the code implemented in https://github.com/hashicorp/vault/pull/13133 will error if the first message event is not the one Vault expects. This PR effectively inverses the `if` statement so that the `while` loop will function properly and wait for the proper event to catch.

![image](https://user-images.githubusercontent.com/28541758/204567129-807e9c9b-1f3a-4bcd-af76-c987e9332843.png)

![image](https://user-images.githubusercontent.com/28541758/204566813-b66eddad-0e96-4c36-8c81-4106d1b217fc.png)

2022-11-29 15:18 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=18138)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=18138)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=18138).</sub>

2022-11-29 15:35 UTC, hashishaw commented
Thank you for this contribution @DavidSpek! Would you please add a [changelog](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md#changelog-entries) file and we can get this merged?

2022-11-29 16:07 UTC, DavidSpek commented
@hashishaw Thanks for the extremely quick response. I've added a changelog file and I believe all CI checks have passed.

2022-11-29 17:24 UTC, DavidSpek commented
I'm not sure why that docker CI test is failing. I don't think it is related to this code change.

2022-12-01 10:57 UTC, DavidSpek commented
@hashishaw friendly reminder ping as I know how easy it is for a PR to get lost in the noise.

2022-12-19 11:18 UTC, DavidSpek commented
@hashishaw @austingebauer Friendly reminder that this PR is still pending.

2022-12-19 16:00 UTC, austingebauer commented
@DavidSpek @hashishaw - I can give this a review / test as well 👍

2022-12-20 00:40 UTC, austingebauer approved these changes

2022-12-20 19:16 UTC, hashishaw requested changes
Thank you for this change! It does look like this breaks a couple UI tests, which is expected because we had tests checking that the error callback is triggered when the origin is untrusted or not the same window. 

Unfortunately the github checks do not reflect that, since we skip the UI tests under the hood if the branch is not prefixed with `ui/`. So I have two requests:
1. If you would please [rename the branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to `ui/oidc-event-filter` that would let us confirm that the tests are all passing from our CircleCI workflow
2. We should update the tests to make sure that any messages with untrusted origins or non-matching origins are ignored. 
Thanks again! Let me know if you have any trouble testing locally, and our [testing README](https://github.com/hashicorp/vault/blob/main/ui/README.md#running-tests) might be helpful here.

2022-12-22 12:31 UTC, closed without merging

2022-12-22 12:34 UTC, DavidSpek commented
Since renaming the branch causes this PR to be closed, please have a look at https://github.com/hashicorp/vault/pull/18521.