Server: add and support unix listener (UDS)
hashicorp/vault pull request #18227
Opened 2022-12-05 16:21 UTC by shaj13

Fix #5491  

hcl config
```text
listener "unix" {}

listener "tcp" {
  address       = "127.0.0.1:8300"
  tls_cert_file = ""
  tls_key_file  = ""
  tls_disable   = 1
}

api_addr     = "http://127.0.0.1:8300"
cluster_addr = "http://127.0.0.1:8300"

storage "file" {
  path           = "/tmp/vault/storage"
  connection_url = ""
  ha_enabled     = false
}
```

Vault server logs: 
```sh
==> Vault server configuration:

             Api Address: http://127.0.0.1:8300
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8301
   Environment Variables: DBUS_SESSION_BUS_ADDRESS, HOME, LANG, LC_CTYPE, LOGNAME, MOTD_SHOWN, OLDPWD, PATH, PWD, SHELL, SHLVL, SSH_CLIENT, SSH_CONNECTION, SSH_TTY, TERM, USER, XDG_DATA_DIRS, XDG_RUNTIME_DIR, XDG_SESSION_CLASS, XDG_SESSION_ID, XDG_SESSION_TYPE, _
              Go Version: go1.19.3
              Listener 1: unix (max_request_duration: "1m30s", max_request_size: "33554432")
              Listener 2: tcp (addr: "127.0.0.1:8300", cluster address: "127.0.0.1:8301", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: file
                 Version: Vault v1.13.0-dev1, built 2022-12-02T16:02:28Z
             Version Sha: 12b2fab87559d6da9ff38247902a540992867827+CHANGES

==> Vault server started! Log data will stream in below:

2022-12-05T18:20:16.511+0200 [INFO]  vault: proxy environment: http_proxy="" https_proxy="" no_proxy=""
2022-12-05T18:20:16.512+0200 [INFO]  vault.core: Initializing version history cache for core
```

Curl Example 
```sh
curl --silent -XGET --unix-socket /run/vault.sock http://localhost/v1/sys/health | jq
{
  "initialized": false,
  "sealed": true,
  "standby": true,
  "performance_standby": false,
  "replication_performance_mode": "unknown",
  "replication_dr_mode": "unknown",
  "server_time_utc": 1670257271,
  "version": "1.13.0-dev1"
}
```

2022-12-06 19:01 UTC, shaj13 commented
@raskchanky PTAL, 
`TestBackend_StaticRole_LockRegression` fail, can re-run the job ?.

2022-12-07 18:29 UTC, raskchanky reviewed
Thanks for working on this! I think it looks great and would love to get it merged. Before doing so though, I think we need some documentation. Would you be up for writing some docs for this change? Specifically:

* https://developer.hashicorp.com/vault/docs/configuration/listener should mention there's now multiple listener types and should link to a new page for the UDS listener, similar to the TCP one.
* A new page, similar to https://developer.hashicorp.com/vault/docs/configuration/listener/tcp but obviously less involved, mentioning what a Unix domain socket is, the available listener parameters that can be configured, and a few code examples. I also think your example showing how to connect to Vault over a UDS with curl would be an excellent addition.

If you've never written Vault docs before, the [website README](https://github.com/hashicorp/vault/blob/main/website/README.md) has docs that show how to run the site locally via docker.

2022-12-07 23:34 UTC, shaj13 commented on changelog/18227.txt
> +**Server UDS Listener**: Adding listener to vault server to serve http request vi unix domain socket
done

2022-12-07 23:37 UTC, shaj13 commented
> Thanks for working on this! I think it looks great and would love to get it merged. Before doing so though, I think we need some documentation. Would you be up for writing some docs for this change? Specifically:
> 
>     * https://developer.hashicorp.com/vault/docs/configuration/listener should mention there's now multiple listener types and should link to a new page for the UDS listener, similar to the TCP one.
> 
>     * A new page, similar to https://developer.hashicorp.com/vault/docs/configuration/listener/tcp but obviously less involved, mentioning what a Unix domain socket is, the available listener parameters that can be configured, and a few code examples. I also think your example showing how to connect to Vault over a UDS with curl would be an excellent addition.
> 
> 
> If you've never written Vault docs before, the [website README](https://github.com/hashicorp/vault/blob/main/website/README.md) has docs that show how to run the site locally via docker.

@raskchanky  Website and docs have been updated as well 

<img width="929" alt="image" src="https://user-images.githubusercontent.com/65346528/206320335-9006a5b5-0189-4074-84dc-52b35c0f6d2c.png">

2022-12-08 01:48 UTC, raskchanky reviewed
The documentation looks great! Thanks for writing it up. I left a bunch of minor copy edits.

2022-12-08 01:48 UTC, raskchanky commented on website/content/docs/configuration/listener/index.mdx
> +- [Unix][unix]
```suggestion
- [Unix Domain Socket][unix]
```

2022-12-08 01:48 UTC, raskchanky commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_mode` `(string: "")` – When specified, change the access
```suggestion
- `socket_mode` `(string: "")` – When specified, changes the access 
```

2022-12-08 01:48 UTC, raskchanky commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_user` `(string: "")` – When specified, change the user owner of unix socket.
```suggestion
- `socket_user` `(string: "")` – When specified, changes the user owner of the unix socket.
```

2022-12-08 01:48 UTC, raskchanky commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_group` `(string: "")` – When specified, change the group owner of unix socket.
```suggestion
- `socket_group` `(string: "")` – When specified, changes the group owner of the unix socket.
```

2022-12-08 01:48 UTC, raskchanky commented on website/content/docs/configuration/listener/unix.mdx
> +This example shows Vault listening on tcp localhost, as well as unix socket.
```suggestion
This example shows Vault listening on TCP localhost, as well as unix socket.
```

2022-12-08 01:48 UTC, raskchanky commented on website/content/docs/configuration/listener/unix.mdx
> +This example shows changeing access permissions and ownership of unix socket.
```suggestion
This example shows changing access permissions and ownership of the unix socket.
```

2022-12-08 14:06 UTC, shaj13 commented
> The documentation looks great! Thanks for writing it up. I left a bunch of minor copy edits.

fantastic, typo removed and docs updated per your suggestion 👍

2022-12-08 16:22 UTC, tjperry07 requested changes
Minor feedback.

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +  The Unix listener configures Vault to listen on the specified unix domain socket.
```suggestion
  The Unix listener configures Vault to listen on the specified Unix domain socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +  The Unix listener configures Vault to listen on the specified unix domain socket.
Unix is a brand name, like Nike. But not UNIX because we aren't using the trademark

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +The unix listener configures Vault to listen on the specified unix domain socket.
```suggestion
The Unix listener configures Vault to listen on the specified Unix domain socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +- `address` `(string: "/run/vault.sock")` – Specifies the address to bind the unix domain socket.
```suggestion
- `address` `(string: "/run/vault.sock")` – Specifies the address to bind the Unix domain socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +  permissions and the special mode flags of the unix socket.
```suggestion
  permissions and the special mode flags of the Unix socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_group` `(string: "")` – When specified, changes the group owner of the unix socket.
```suggestion
- `socket_user` `(string: "")` – When specified, changes the user owner of the Unix socket.

- `socket_group` `(string: "")` – When specified, changes the group owner of the Unix socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +This example shows Vault listening on TCP localhost, as well as unix socket.
```suggestion
This example shows Vault listening on TCP localhost, as well as Unix socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +This example shows changing access permissions and ownership of the unix socket.
```suggestion
This example shows changing access permissions and ownership of the Unix socket.
```

2022-12-08 16:22 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_group` `(string: "")` – When specified, changes the group owner of the unix socket.
Are these optional?

2022-12-08 17:46 UTC, raskchanky commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_group` `(string: "")` – When specified, changes the group owner of the unix socket.
Yes

2022-12-08 18:13 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_user` `(string: "")` – When specified, changes the user owner of the unix socket.
```suggestion
- `socket_user` `(string: "", <optional>)` – Changes the user owner of the Unix socket.
```

2022-12-08 18:13 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_group` `(string: "")` – When specified, changes the group owner of the unix socket.
```suggestion
- `socket_group` `(string: "", <optional>)` – Changes the group owner of the unix socket.
```

2022-12-08 18:16 UTC, tjperry07 commented on website/content/docs/configuration/listener/unix.mdx
> +- `socket_group` `(string: "")` – When specified, changes the group owner of the unix socket.
```suggestion
- `address` `(string: "/run/vault.sock", <required>)` – Specifies the address to bind the Unix domain socket.

- `socket_mode` `(string: "", <optional>)` – Changes the access
  permissions and the special mode flags of the unix socket.

- `socket_user` `(string: "", <optional>)` – Changes the user owner of the Unix socket.

- `socket_group` `(string: "", <optional>)` – Changes the group owner of the Unix socket.
```

2022-12-08 18:17 UTC, tjperry07 requested changes
Just merge the unix and definition changes and it's good to go

2022-12-09 19:08 UTC, shaj13 commented
@raskchanky @tjperry07 PTAL, docs updated

2022-12-09 20:17 UTC, tjperry07 approved these changes

2022-12-09 20:28 UTC, merged