pki: ensure default issuer is set
hashicorp/vault pull request #19211
Opened 2023-02-16 13:17 UTC by nsimons

If the issuer that is being imported already exists **and** this is the only issuer within the PKI backend, then ensure default issuer is set.

Fixed #19210

2023-02-16 16:02 UTC, cipherboy requested changes
I believe with more testing, you'll find this patch doesn't do what you're intending. :-) In particular, this patch is at too low of a level or requires much more invasive changes, to know whether or not we're importing only one issuer (of which, this is the first), or if we're importing multiple.

Consider:

 - A root issuer already exists in the mount, without key material, and is not default.
 - `/issuers/import/bundle` is called, importing a bundle of `existing root cert, int key, int cert`.

The first call to `importIssuer` would thus set the default (as there's one known issuer and this one was already known), but the intermediate (with key material!) should instead be the default issuer, as the former lacks key material and thus couldn't be used for signing leaf certs.

Consider also:

- No issuers exist in this mount, but a key exists.
- `/issuers/import/bundle` is called, importing a bundle of `root, same root, int cert`.

This is functionally equivalent to the above call (perhaps they accidentally concat'd `issuing_ca` with `ca_chain` field on intermediate issuance), and again results in `root` getting the default key, prevent intermediate from correctly taking it, as the rest of the existing logic would ensure. 

I believe this is handled via the [`default_follows_latest_issuer` parameter](https://developer.hashicorp.com/vault/api-docs/secret/pki#default_follows_latest_issuer) in general, when the importIssuer operations succeed.

Lastly, regarding the posted issue, note our previous discussions on (present lack of) transactional write support.

2023-02-17 07:57 UTC, nsimons commented
Argh, too many different use cases now post-1.11 ;) Thanks for the detailed comment!

Right, I did think about the key but I noticed that there was a branch in the code that [warns](https://github.com/hashicorp/vault/blob/v1.12.3/builtin/logical/pki/path_manage_issuers.go#L292) the operator in case the private key was missing, so I thought this was a valid sequence that is allowed to happen. But I agree, not the best place to check this.

What about doing it at the end of `pathImportIssuers` then, with the other checks? We could get all the issuers, all the keys, if there is one and only one match across the issuer-key pair then set default issuer.

I'm trying to get the calls a bit more predictable, in pre-1.11 you could retry `pki/intermediate/set-signed` and everything would work, but now you'd have to use something like `/pki/config/issuers` instead to ensure that default issuer is set.

2023-02-17 14:07 UTC, cipherboy commented
@nsimons To get this type of consistency in an easily achievable manner, I think you'll find waiting for transactional storage support to be far easier than attempting to achieve storage consistency without proper transactional write capabilities. :-) 

The best I can advise you to do, and perhaps the best thing to do anyways, is simply move the CRL rebuild after the default setting (at the end of the if it is nested in). 

This moves the default setting closer to the issuer import, so if issuer import succeeds, it is more likely that default setting will succeed since it is quick and easy, but if issuer import fails, its likely that there's at least one issuer left to create. Then, we can do the CRL rebuild and fail appropriately.

IMO, this would be the closest to this you could achieve without implementing transactional storage and relying on that to bail earlier operations when later operations fail. My 2c. 

(Nominally, I think it is also the more correct thing to do, as the act of setting a default issuer does influence the CRL building).

2023-02-17 14:56 UTC, nsimons commented
Right, makes sense. Unfortunately that will not help in our use case. We basically use the steps from the [tutorial](https://developer.hashicorp.com/vault/tutorials/secrets-management/pki-engine#step-2-generate-intermediate-ca) to generate the intermediate CA, i.e. generating the CSR, signing it, setting it. So there's only one issuer, and if this issuer get's imported half-way it will not be set as default (default in this case is set within `importIssuer`, not in `pathImportIssuers`).  On the second go-around, the issuer already exists, so we will never enter the `if len(createdIssuers) > 0` that contains CRL rebuild and default issuer update procedures. Heh, so actually the CRL will not get rebuilt either in this case :)

Anyway, I'm happy to make the change as you suggested, in case it helps in another use case. Just curious, is transactional storage support actually something on the Vault roadmap, or just a nice if it existed but not really feasible? Because it would definitely be a feature we would be interested in (as you have already gathered from my previously opened issues).

2023-07-31 06:33 UTC, closed without merging