VAULT-15546 First pass at Vault Proxy docs
hashicorp/vault pull request #20578
Opened 2023-05-12 20:23 UTC by VioletHynes

2023-05-12 20:37 UTC, VioletHynes commented on website/content/api-docs/index.mdx
Apologies for the whitespace changes on this file, though it seems to be pretty much only affecting this file. The only salient change is at the bottom, line 317.

2023-05-15 20:19 UTC, stevendpclark commented
Hi Violet, will this not break any bookmarked links, outside references to all the existing agent pages? Is that something we want to do?

2023-05-15 20:29 UTC, VioletHynes commented
> Hi Violet, will this not break any bookmarked links, outside references to all the existing agent pages? Is that something we want to do?

Hi there, and yeah, you're right that this PR will have this impact. Ultimately, I don't see a way to avoid this without duplicating a lot of existing pages. For example, auto-auth is something that's no longer Agent specific, so unless we move it out of the Agent category, we'd need to duplicate it in a new category, or it would appear mischaracterized. 

Furthermore, the index of today's Agent page talks about why a customer might need Agent/Proxy - it makes a lot of sense to me for that kind of discussion to be in a meta-category. I guess, to put it another way, I feel like there's no good way to preserve existing links while maintaining well-organized docs, though it's possible I've missed something (or that others might feel different).

I've already looped in the Education team for review on this PR, as this is a larger reaching docs PR than normal, and am planning to review with them first. Hopefully, we can determine whether or not this new structure is the right path forward!

2023-05-16 12:52 UTC, stevendpclark commented
Thanks for the explanation @VioletHynes, makes perfect sense and I agree the new layout is better going forward. I think we could possibly leverage a [Vercel redirect](https://vercel.com/docs/concepts/edge-network/redirects) to cover the majority of these pages without having to duplicate the docs. 

Within [website/redirects.js](https://github.com/hashicorp/vault/blob/main/website/redirects.js) I added this and it *seemed* to work, I haven't checked if this covers all pages 
```
{
  source: '/vault/docs/agent/:slug',
  destination: '/vault/docs/agentandproxy/agent/:slug',
  permanent: true,
}
```

2023-05-16 13:00 UTC, VioletHynes commented
> Thanks for the explanation @VioletHynes, makes perfect sense and I agree the new layout is better going forward. I think we could possibly leverage a [Vercel redirect](https://vercel.com/docs/concepts/edge-network/redirects) to cover the majority of these pages without having to duplicate the docs.
> 
> Within [website/redirects.js](https://github.com/hashicorp/vault/blob/main/website/redirects.js) I added this and it _seemed_ to work, I haven't checked if this covers all pages
> 
> ```
> {
>   source: '/vault/docs/agent/:slug',
>   destination: '/vault/docs/agentandproxy/agent/:slug',
>   permanent: true,
> }
> ```

Oh this is great! Thanks for calling this out, I'll give this a go.

2023-05-16 15:39 UTC, VioletHynes commented
Updated the PR with redirection! I needed to be a bit more explicit with the redirection since not all `agent` stuff moved to `agentandproxy/agent` (e.g. auto-auth). Thanks a lot @stevendpclark for the suggestion!

2023-05-16 16:32 UTC, brianshumate requested changes
This all makes sense to me and looks great so far. I have only a couple minor suggestions!

2023-05-16 16:32 UTC, brianshumate commented on website/content/docs/agentandproxy/autoauth/sinks/index.mdx
> +configured Sinks, subject to their configuration. Today, we only support one
```suggestion
enabled Sinks, subject to their configuration. Today, we only support one
```

2023-05-16 16:50 UTC, VioletHynes commented on website/content/docs/agentandproxy/autoauth/methods/cert.mdx
> +config stanza, Agent and Proxy will fall back to using TLS settings from thir respective
Good catch! Fixed, and pushed.

2023-05-16 16:50 UTC, VioletHynes commented on website/content/docs/agentandproxy/autoauth/sinks/index.mdx
> +configured Sinks, subject to their configuration. Today, we only support one
Good catch! Fixed, and pushed.

2023-05-16 18:48 UTC, brianshumate approved these changes

2023-05-17 00:37 UTC, yhyakuna reviewed
Great work!  I agree with the need for these changes. 

Please see https://github.com/hashicorp/vault/pull/20612 for my suggestions. If you don't agree with my suggestions, feel free to let me know or make changes.  

I wish I had a diagram for API Proxy, but I couldn't find one... :(

2023-05-17 15:32 UTC, jonathanfrappier commented on website/content/docs/agentandproxy/index.mdx
> +Auto-Auth functionality takes place within an `auto_auth` configuration stanza.
Is it worth providing an example here, or linking to an example of the configuration stanza?

2023-05-17 19:54 UTC, yhyakuna approved these changes

2023-05-19 17:11 UTC, merged