Docs for Application Default Credentials, links to non-dwdoa setup
hashicorp/vault pull request #21453
Opened 2023-06-26 07:47 UTC by torfjor

2023-07-03 20:44 UTC, austingebauer reviewed
Looking good. Left a few suggestions. Thanks for opening this!

2023-07-03 20:44 UTC, austingebauer commented on website/content/docs/auth/jwt/oidc-providers/google.mdx
> +- [DWDoA](https://developers.google.com/workspace/guides/create-credentials#service-account)
```suggestion
- [With Domain-Wide Delegation of Authority](https://developers.google.com/workspace/guides/create-credentials#service-account)
```

2023-07-03 20:44 UTC, austingebauer commented on website/content/docs/auth/jwt/oidc-providers/google.mdx
> +- [Without DWDoA](https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd)
```suggestion
- [Without Domain-Wide Delegation of Authority](https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd)
```

2023-07-03 20:44 UTC, austingebauer commented on website/content/docs/auth/jwt/oidc-providers/google.mdx
> +  The service account vault is running under must be granted the `iam.serviceAccounts.signJwt` permission on this service account.
```suggestion
  The service account Vault is running under must be granted the `iam.serviceAccounts.signJwt` permission on this service account.
```

2023-07-03 20:44 UTC, austingebauer commented on website/content/docs/auth/jwt/oidc-providers/google.mdx
>  In **step 11** within the section titled
```suggestion
In **step 5e** within the section titled
```

2023-07-06 23:53 UTC, schavis requested changes

2023-07-06 23:53 UTC, schavis commented on website/content/docs/auth/jwt/oidc-providers/google.mdx
> +Google Workspace Domain-Wide Delegation of Authority for authentication and authorization, or group admin roles granted to a GCP service account.
```suggestion
Vault uses one of the following methods to fetch Google Workspace groups and user information:

- Google Workspace Domain-Wide Delegation of Authority for authentication and authorization
- Group admin roles granted to a GCP service account.
```

Suggest simplifying to make the text easier to scan and parse.

2023-07-12 22:53 UTC, austingebauer commented
@torfjor - Curious if you'd be able to apply some of the suggestions here? If not, I'm happy to merge this PR and take over with the final edits. Thanks!

2023-08-07 23:13 UTC, austingebauer commented
@torfjor - I'm going to go ahead and merge this. I'll fix up the docs myself for the upcoming release.

2023-08-07 23:14 UTC, austingebauer approved these changes

2023-08-07 23:14 UTC, merged