[Docs] Client count doc updates for ACME update in 1.14
hashicorp/vault pull request #21541
Opened 2023-06-30 22:38 UTC by schavis

Changes:
- Rewrote "Client count" overview to focus on a discussion of how entity assignment works and added ACME-related text.
- Re-titled "Client count" page to "Clients and entities".
- Moved content that focuses on the calculations to a new document called "Client count calculation" and rewrote the text to reference language and concepts in the client count overview.
- Moved the best practices discussion for CI/CD pipelines to a new best practices  document (with minimal edits) called "Best practices for CI/CD pipelines" under /secrets/pki/best-practices/cicd-pipelines"
- Updated TOC

2023-07-06 19:19 UTC, cipherboy approved these changes
Thank you very much! The ACME client count updates look correct to me :-)

2023-07-06 19:37 UTC, cipherboy commented on website/content/docs/concepts/client-count/index.mdx
> +Platform- or server-based  | Kubernetes, AWS, GCP, Azure, PKI, Cloud Foundry
```suggestion
Platform- or server-based  | Kubernetes, AWS, GCP, Azure, Cert, Cloud Foundry
```

PKI is a secrets engine, not an auth engine; Cert is the auth engine.

2023-07-06 19:38 UTC, cipherboy commented on website/content/docs/concepts/client-count/index.mdx
> +ACME                       | Certificate
```suggestion
```

2023-07-06 19:38 UTC, cipherboy commented on website/content/docs/concepts/client-count/index.mdx
> +When clients authenticate, Vault assigns them a **client identity type**:
Mohan: This comment from the original made sense here about why:

> There can be many different types of clients that authenticate and communicate with Vault using one of the above identities, including:

2023-07-06 19:39 UTC, brianshumate requested changes
Looks great! I found just one typo and good to go from me.

2023-07-06 19:39 UTC, brianshumate commented on website/content/docs/concepts/client-count/counting.mdx
> +- An application authenticating with AppRol receive the same entity assignment
```suggestion
- An application authenticating with AppRole receive the same entity assignment
```

2023-07-06 19:40 UTC, cipherboy commented on website/content/docs/concepts/client-count/index.mdx
> +Client identity type       | AuthN method
```suggestion
Authorization Source       | AuthN method
```

2023-07-07 12:32 UTC, brianshumate approved these changes

2023-07-07 12:32 UTC, merged