Added lease quota count and rate limit count docs
hashicorp/vault pull request #22509
Opened 2023-08-22 19:32 UTC by divyaac

PR: https://github.com/hashicorp/vault-enterprise/pull/4552/files

2023-08-22 19:36 UTC, VioletHynes commented on website/content/api-docs/system/lease-count-quotas.mdx
> +or if a value for `role` is specified. All global quotas are inheritable by default. All namespace quotas
I think I'd suggest rewording this for clarity, especially as we made the decision that root quotas can't be made uninheritable:
"All global quotas are inheritable by default. All namespace quotas are not inheritable by default."
-> 
"Root namespace quotas are inheritable by default and this cannot be changed, thereby making them global in reach. All other namespace quotas are not inheritable by default."

2023-08-22 19:36 UTC, VioletHynes commented on website/content/api-docs/system/lease-count-quotas.mdx
> +- `inheritable` `(bool: false)` - If set to `true` on a quota where `path` is set to a namespace,
```suggestion
- `inheritable` `(bool: false)` - If set to `true` on a quota where `path` is set to a non-root namespace,
```

2023-08-22 19:37 UTC, VioletHynes commented on website/content/api-docs/system/lease-count-quotas.mdx
> +- `inheritable` `(bool: false)` - If set to `true` on a quota where `path` is set to a namespace,
Wait, actually, this doesn't make sense. Removing this suggestion.

2023-08-22 19:38 UTC, VioletHynes commented on website/content/api-docs/system/lease-count-quotas.mdx
> +or if a value for `role` is specified. All global quotas are inheritable by default. All namespace quotas
```suggestion
all child namespaces of the specified path namespace will inherit this quota. `inheritable` cannot be set to true if the path does not specify a namespace. All global quotas are inheritable by default. All namespace quotas
```

2023-08-22 19:39 UTC, VioletHynes commented on website/content/api-docs/system/lease-count-quotas.mdx
> +or if a value for `role` is specified. All global quotas are inheritable by default. All namespace quotas
Suggested rewording of the "This will fail" section. In particular, `role` can never be applied on a namespace path anyway

2023-08-22 20:26 UTC, VioletHynes approved these changes
Looks great!

2023-08-23 18:16 UTC, schavis requested changes

2023-08-23 18:16 UTC, schavis commented on website/content/api-docs/system/lease-count-quotas.mdx
> +  all child namespaces of the specified path namespace will inherit this quota. `inheritable` cannot be set to
```suggestion
  all child namespaces of the specified path namespace will inherit the quota. The `inheritable` parameter cannot be set to
```

Style correction: avoid "this" as a pronoun

2023-08-23 18:16 UTC, schavis commented on website/content/api-docs/system/lease-count-quotas.mdx
> +  All other namespace quotas are not inheritable by default.
```suggestion
  `true` if the `path` does not specify a namespace. Only the quotas associated
  with the root namespace are inheritable by default.
```

2023-08-23 18:16 UTC, schavis commented on website/content/api-docs/system/rate-limit-quotas.mdx
> +  All other namespace quotas are not inheritable by default.
```suggestion
- `inheritable` `(bool: false)` - If set to `true` on a quota where `path` is set to a namespace,
  all child namespaces of the specified path namespace will inherit the quota. The `inheritable`
  parameter cannot be set to `true` if the `path` does not specify a namespace. Only quotas
  associated with the root namespace quotas are inheritable by default.
```

Same suggestions as for the other file

2023-08-23 23:37 UTC, schavis approved these changes

2023-08-23 23:40 UTC, merged