Add administrative namespace docs
hashicorp/vault pull request #22581
Opened 2023-08-28 14:48 UTC by biazmoreira

2023-08-28 15:24 UTC, ccapurso approved these changes
Looks great! You made it very easy to review with the partial usage.

2023-08-28 15:24 UTC, maxb commented on website/content/api-docs/system/auth.mdx
> -This endpoint reads the given auth path's configuration. _This endpoint requires
A line has been erroneously deleted here

2023-08-28 17:29 UTC, divyaac approved these changes

2023-08-29 15:58 UTC, schavis requested changes
Looks good overall. Made some suggestions to address styleguide issues.

2023-08-30 16:29 UTC, schavis commented on website/content/api-docs/system/auth.mdx
> +- This endpoint reads the given auth path's configuration. _This endpoint requires
```suggestion
- This endpoint reads the given auth path's configuration. This endpoint requires
```

2023-08-30 16:31 UTC, merged