Feature/document tls servername
hashicorp/vault pull request #22714
Opened 2023-08-31 22:37 UTC by in0rdr

Hi @schavis,

Thanks for your review on https://github.com/hashicorp/vault/pull/12982

I was unable to apply your suggestions because I deleted the fork with the local change previously.

In any case, find here the update with all the suggestions.

The suggestions are really helpful, so If you find anything else we could improve just let us know.

Thanks

2023-08-31 23:07 UTC, schavis requested changes

2023-08-31 23:07 UTC, schavis commented on website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
> +```
I'm not sure having this as an independent section is useful. What do you think of dropping the heading and making it the second paragraph in the introduction? That way you're outlining the situation in the first paragraph, showing the symptom in the second paragraph, then introducing your example solutions.

2023-08-31 23:07 UTC, schavis commented on website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
> +If you have a load balancer for your Vault cluster, you can add  a single
```suggestion
If you have a load balancer for your Vault cluster, you can add a single
```

Remove stray space

2023-08-31 23:10 UTC, schavis requested changes

2023-08-31 23:10 UTC, schavis commented on website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
> +TLS](/docs/concepts/integrated-storage#integrated-storage-and-tls) covers the
```suggestion
TLS](/vault/docs/concepts/integrated-storage#integrated-storage-and-tls) covers the
```

2023-08-31 23:10 UTC, schavis commented on website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
> +Storage](/docs/platform/k8s/helm/examples/ha-with-raft) to build the cluster.
```suggestion
Storage](/vault/docs/platform/k8s/helm/examples/ha-with-raft) to build the cluster.
```

2023-08-31 23:10 UTC, schavis commented on website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
> +TLS](/docs/platform/k8s/helm/examples/standalone-tls) to create a TLS
```suggestion
TLS](/vault/docs/platform/k8s/helm/examples/standalone-tls) to create a TLS
```

2023-08-31 23:10 UTC, schavis commented on website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
> +[`leader_tls_servername`](/docs/configuration/storage/raft#leader_tls_servername)
```suggestion
[`leader_tls_servername`](/vault/docs/configuration/storage/raft#leader_tls_servername)
```

2023-08-31 23:13 UTC, schavis commented
> I was unable to apply your suggestions because I deleted the fork with the local change previously.

D'oh! Thanks for taking the time to resubmit the PR! I added some additional comments. Most are fixes for the links that I missed the first time through.

Also, I forgot to mention on the older PR that you'll need to also update the TOC file (/website/data/docs-nav-data.json) so the new doc shows up in the left-hand navigation. The Helm examples section is currently around ~line 1761

2023-09-01 05:54 UTC, in0rdr commented
Thanks a lot for the review, I learn a lot about how these docs pages are being built.

Also, I have to admit that I like the example much better now, thanks for the suggestions :smile: 

I also decided to make the page title a bit more similar to the the existing documentation examples, mostly because we reference two examples in the text.

2023-09-01 06:02 UTC, in0rdr commented on website/data/docs-nav-data.json
>                    },
I decided to put the link in the sidebar right after the existing two examples

2023-09-01 18:33 UTC, schavis approved these changes

2023-09-01 18:33 UTC, schavis commented
LGTM! Feel free to merge

2023-09-02 21:18 UTC, in0rdr commented
Thanks @schavis I did a rebase but I'm not authorized to merge/deploy. Can you take care of this? Thank you.

2023-09-12 20:08 UTC, schavis commented
> Thanks @schavis I did a rebase but I'm not authorized to merge/deploy. Can you take care of this? Thank you.

Apologies for the delay, I was out sick last week. I'll get this merged today.

2023-09-12 20:09 UTC, merged