Address issue #22722 to add allow_organizations to cert credential backend for TLS certificate auth
hashicorp/vault pull request #22735
Opened 2023-09-01 16:46 UTC by alakahakai

Address issue #22722 to add allow_organizations to cert credential backend for TLS certificate auth

2023-09-01 16:46 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=22735)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=22735)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=22735).</sub>

2023-09-11 18:16 UTC, alakahakai commented
@hsimon-hashicorp Thanks for tagging this PR. Could you please kindly advise on the timeline of the PR review? Thanks.

2023-09-20 17:57 UTC, alakahakai commented
@hsimon-hashicorp Ping for updates. Thank you!

2023-10-05 15:36 UTC, alakahakai commented
@hsimon-hashicorp Ping for updates again. Thank you!

2023-12-14 03:56 UTC, alakahakai commented
@schavis Ping for updates again. Thank you!

2024-02-02 18:32 UTC, alakahakai commented
@hsimon-hashicorp @schavis Ping for updates again. Thank you!

2024-04-15 20:19 UTC, stevendpclark requested changes
@alakahakai thanks for the contribution and I apologize about the delay getting to it. 

Overall the feature looks great! This just needs an [improvement changelog](https://github.com/hashicorp/vault/blob/main/changelog/README.md) entry and I've left a comment about one change that I think we should remove.

2024-04-15 20:19 UTC, stevendpclark commented on builtin/credential/cert/path_login.go
> +		for _, name := range clientCert.Subject.OrganizationalUnit {
Can you expand on this change?
 
I don't think I agree the existing `allowed_names` configuration entries should be matching against organization unit/organization fields. These should only be matched against their respective configurations `allowed_organizational_units` and the new `allowed_organizations`.

2025-08-06 22:42 UTC, doty-db commented on builtin/credential/cert/path_login.go
> +		for _, name := range clientCert.Subject.OrganizationalUnit {
@stevendpclark This is just a continuation of the existing policy in this code. A name in `allowed_names` is already allowed to match:

- The certificate's `CommonName`.
- A DNS name in the certificate's `DNSNames`.
- An email address in the certificate's `EmailAddresses`.

This simply extends the lenient policy to cover the other filters as well.

(I'm sorry for reviving this extremely old PR. Due to unfortunate circumstances this got dropped on the floor on our side, but since we've actually been using it in production for over a year I'm going to try to get this resolved. 😅)

2025-08-06 23:05 UTC, doty-db commented on builtin/credential/cert/path_login.go
> +		for _, name := range clientCert.Subject.OrganizationalUnit {
Actually, given the fact that I can't actually do anything with this PR I've opened https://github.com/hashicorp/vault/pull/31440 as a modern replacement.

2025-08-07 20:36 UTC, heatherezell commented on builtin/credential/cert/path_login.go
> +		for _, name := range clientCert.Subject.OrganizationalUnit {
@doty-db Should we go ahead and close this PR then? Let me know. :) I've added your new PR to our backlog and I'll bring it up in our next planning meeting. Thanks!

2025-08-07 20:59 UTC, doty-db commented on builtin/credential/cert/path_login.go
> +		for _, name := range clientCert.Subject.OrganizationalUnit {
Yes please.

2025-08-07 21:34 UTC, heatherezell commented
Closing as this PR is superseded by https://github.com/hashicorp/vault/pull/31440.

2025-08-07 21:34 UTC, closed without merging