updated the LIST identity/entity-alias/id endpoint docs
hashicorp/vault pull request #23016
Opened 2023-09-12 19:14 UTC by nicolaka

I updated the LIST identity/entity-alias/id endpoint docs to include details on new data that the endpoint returns.

2023-09-12 19:42 UTC, schavis requested changes

2023-09-12 19:42 UTC, schavis commented on website/content/api-docs/secret/identity/entity-alias.mdx
> +This endpoint returns a list of available entity aliases and key data by their identifiers.
```suggestion
The list by ID endpoint returns the available entity aliases and key data by their identifiers.
```
Style correction: avoid "this" as a pronoun

2023-09-13 19:56 UTC, maxb commented on website/content/api-docs/secret/identity/entity-alias.mdx
> +"data": {
Inconsistent indentation:
```suggestion
    "data": {
```

2023-09-14 18:15 UTC, schavis approved these changes

2023-09-18 19:29 UTC, hghaf099 approved these changes

2023-09-18 19:30 UTC, hghaf099 commented
Thanks for the contribution!

2023-09-18 19:30 UTC, merged