Slight rephrase for the association API endpoints
hashicorp/vault pull request #23393
Opened 2023-09-28 20:14 UTC by maxcoulombe

2023-09-28 20:32 UTC, robmonte approved these changes

2023-09-28 20:50 UTC, schavis requested changes

2023-09-28 20:50 UTC, schavis commented on website/content/api-docs/system/secrets-sync.mdx
> +or retry a failed sync operation if the underlying problem that caused the failure is now resolved.
```suggestion
The set endpoint links a secret to an existing destination using the secret name
and mount path and triggers a sync operation. If the secret is already
associated with the destination, Vault performs a refresh without recreating the
link. Triggering a refresh is useful to push the secret to external systems
or retry a failed sync operation if the underlying problem that caused the
failure has been resolved.
```

Style correction: write in active voice, make it clear what takes action

2023-09-28 20:50 UTC, schavis commented on website/content/api-docs/system/secrets-sync.mdx
> +or if the secret no longer exists on the external system, the remove operation still succeeds.
```suggestion
The remove endpoint unlinks a secret from an existing destination based on the
secret name and mount path, and triggers an unsync operation. Unsyc
operations delete the secret from the external system. The unsyc operation
reports success if the targeted association is removed, does not exist, or the
secret was already removed form the external system.
```

Style correction: write in active voice, make it clear what takes action

2023-09-28 21:35 UTC, austingebauer approved these changes

2023-10-05 13:19 UTC, maxcoulombe commented
Hey @schavis ! The requested changes were applied would it be possible to get a 2nd review?

2023-10-05 17:11 UTC, schavis approved these changes

2023-10-05 17:26 UTC, schavis approved these changes

2023-10-05 18:53 UTC, merged