Update oracle.mdx missing feature flags
hashicorp/vault pull request #23517
Opened 2023-10-04 20:34 UTC by OneWhoNests

Adding missing feature flags to API doc. 
split_statements and disconnect_sessions.

Related PR
https://github.com/hashicorp/vault-plugin-database-oracle/pull/62

2023-10-05 17:26 UTC, schavis requested changes

2023-10-05 17:26 UTC, schavis commented on website/content/api-docs/secret/databases/oracle.mdx
> +  revocation statements. If set to false, the revocation statements should include session disconnect logic.
```suggestion
- `split_statements` `(boolean: true)` - Indicates that the provided statements
  specified should be split on semi-colons. Set `split_statements` to true to
  specify multiple SQL statements in a single string. Set `split_statements` to
  `false` for complex queries such as stored or inline procedures.

- `disconnect_sessions` `(boolean: true)` -  Indicates the plugin should
  disconnect any open sessions before running revocation statements. If
  `disconnect_sessions` is `false`, the revocation statements **must** include
  session disconnect logic.
```

Style correction: write in active voice with declarative statements

2023-10-05 17:34 UTC, schavis approved these changes

2024-01-22 19:57 UTC, fairclothjm approved these changes
LGTM!

2024-01-22 19:59 UTC, merged