Update Telemetry Docs
hashicorp/vault pull request #23535
Opened 2023-10-05 20:06 UTC by ltcarbonell

2023-10-09 19:53 UTC, schavis requested changes

2023-10-09 19:53 UTC, schavis commented on website/content/partials/telemetry-metrics/vault/replication/fsm/last_remote_wal.mdx
> +gauge       | number  | Index of the last remote write-ahead log.  Note this is not emitted on standby nodes.
```suggestion
gauge       | number  | Index of the last remote write-ahead log.


<Note>
  Standby nodes do not emit `last_remote_wal` details.
</Note>
```

Style correction: avoid "this" as a pronoun.

2023-10-10 17:57 UTC, schavis commented
@ltcarbonell LGTM. If these changes should be public now, make sure to add the backport labels for 1.15, 1.14, and 1.13 so it gets pushed to the published docs, not just main :)

2023-10-10 21:00 UTC, ltcarbonell commented
> @ltcarbonell LGTM. If these changes should be public now, make sure to add the backport labels for 1.15, 1.14, and 1.13 so it gets pushed to the published docs, not just main :)

Sweet thanks! The code changes are going out with the next major release (1.16) so main should be okay.

2023-10-10 21:00 UTC, merged