Link to deprecation notice page in upgrade guide
hashicorp/vault pull request #23569
Opened 2023-10-09 14:14 UTC by lucymhdavies

https://developer.hashicorp.com/vault/docs/deprecation is a very useful one to review during an upgrade, especially if you are making large version jump

2023-10-09 14:15 UTC, lucymhdavies commented
Additionally, it's outside the scope of this PR, but the table on that deprecation page is ever so slightly too wide for the page layout:

<img width="751" alt="image" src="https://github.com/hashicorp/vault/assets/1116529/141e448d-8f71-4017-8258-90107ea48763">

2023-10-09 18:44 UTC, schavis requested changes

2023-10-09 18:44 UTC, schavis commented on website/content/docs/upgrading/index.mdx
> +are removed (or scheduled to be removed).
```suggestion
--------------------------------------------------------------------------------
We also recommend you consult the
[deprecation notices](/vault/docs/deprecation). The notice page includes
a comprehensive list of deprecated features and the Vault versions where
the feature was removed or is scheduled to be removed.
```
Style correction: write in active voice, frame recommendations as recommendations, not commands

2023-10-10 18:07 UTC, schavis approved these changes

2024-05-01 22:17 UTC, schavis commented
Merging with linter errors as the failure isn't relevant to the suggested change (documentation)

2024-05-01 22:17 UTC, merged