Docs update with known issue
hashicorp/vault pull request #23887
Opened 2023-10-27 16:46 UTC by cinthiaconti

Adding a known issue introduced with 1.14.5 where there is a potential that additional logging does not trigger or generate double logs for user lockout.

2023-10-31 22:01 UTC, schavis requested changes
Don't forget to add the backport label for 1.14 and 1.15 so the update publishes to the current docs.

2023-10-31 22:01 UTC, schavis commented on website/content/partials/known-issues/user-lockout-logging.mdx
> +An enhancement introducing additional logging was released in 1.14.5 before intended. There is potential that this additional logging does not trigger or generate double logs.
```suggestion
A logging enhancement released before we intended in 1.14.5. In some cases, additional logging does not trigger or generate double logs. 
```

Style correction: write in active voice

2023-11-13 22:04 UTC, schavis approved these changes

2024-01-09 17:32 UTC, VioletHynes approved these changes
Looks good to me. Resolved some conflicts but it should be good to merge now. Will merge when I can.

2024-01-09 17:32 UTC, merged