Fix small typo in troubleshooting-acme.mdx
hashicorp/vault pull request #24547
Opened 2023-12-14 19:08 UTC by Deathnerd

Found a small typo while troubleshooting my ACME setup

2023-12-14 19:09 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=24547)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=24547)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=24547).</sub>

2023-12-15 14:57 UTC, marcboudreau requested changes
Thank you for your submission! We typically don't include changelog files for documentation only changes. If you could kindly remove the changelog/24547.txt file, I'll be able to merge this fix.

2023-12-18 16:04 UTC, sgmiller approved these changes

2024-03-19 21:26 UTC, ccapurso approved these changes

2024-03-20 13:16 UTC, marcboudreau approved these changes

2024-03-20 13:16 UTC, merged