Add KVv2 known issue to release notes
hashicorp/vault pull request #24632
Opened 2023-12-21 23:02 UTC by schavis

2023-12-21 23:25 UTC, yhyakuna commented on website/content/partials/known-issues/kv2-url-change.mdx
> +engine that affect existing plugin URLs.
I think we need to clarify that we're talking about the Vault UI changes.  

Something like...

```suggestion
Recent improvements to the Vault UI updated the URL structure of the KV v2 secrets engine that affect existing URLs.
```

2023-12-21 23:25 UTC, yhyakuna commented on website/content/partials/known-issues/kv2-url-change.mdx
> +### URL change for KV v2 plugin ((#kv2-url-change))
```suggestion
### URL change for KV v2 secrets engine ((#kv2-url-change))
```

2023-12-27 17:09 UTC, Monkeychip requested changes
This looks good to me, but I do agree with @yhyakuna comments. I'll approve once those are implemented. Thank you for putting this together!

2023-12-27 19:03 UTC, Monkeychip approved these changes

2024-01-02 16:35 UTC, merged