Implements #3069 - allows use of pre-hashed passwords with userpass backend
hashicorp/vault pull request #24651
Opened 2023-12-31 16:28 UTC by Ivan-Roger

This is a cherry-pick of changes suggested in hashicorp/vault#3225.

2023-12-31 16:28 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=24651)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=24651)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=24651).</sub>

2024-02-16 20:36 UTC, schavis requested changes

2024-02-16 20:36 UTC, schavis commented on website/content/api-docs/auth/userpass.mdx
> +- `password_hash` `(string: <required if password is not given>)` - Pre-hashed version of this user's password in bcrypt format. Mutually exclusive with `password`.
```suggestion
- `password_hash` `(string: <required if password is not given>)` - Pre-hashed password for the current user in bcrypt format. Mutually exclusive with `password`.
```

2024-02-16 20:36 UTC, schavis commented on website/content/api-docs/auth/userpass.mdx
> +- `password` `(string: <required if password_hash is not given>)` - The password for the user. Only required when creating the user.
```suggestion
- `password` `(string: <required if password_hash is not given>)` - Password for the current user. Only required when creating the user.  Mutually exclusive with `password_hash`.
```

updated to match the language in `password_hash`

2024-02-21 23:00 UTC, schavis commented
Content changes lgtm. Please make sure to sign the CLA so your changes can be merged once someone from the Vault ENG team signs off on the code changes

2024-02-21 23:42 UTC, schavis approved these changes

2024-03-03 15:36 UTC, Ivan-Roger commented
@schavis Unfortunately the missing CLA signature comes from the original author (I cherry-picked their commit). He does not seem to be active anymore. Would it be possible to bypass his signature ?

2024-03-11 11:24 UTC, peteski22 commented
Hi @Ivan-Roger thanks for trying to get this over the line, as the original contributor hasn't signed the CLA, I'm going to move this on via a different method.

I will close your PR in favour of https://github.com/hashicorp/vault/pull/25862

2024-03-11 11:24 UTC, closed without merging