Let Vault modify dynamodb tables and use pay-per-request billing mode.
hashicorp/vault pull request #25115
Opened 2024-01-29 10:11 UTC by michael-diggin

Fixes Issue #25114. 

This PR introduces support for creating the DynamoDB table that Vault would use with PAY_PER_REQUEST billing mode, and introduces support for allowing Vault to modify the billing mode and read/write capacity of the table if it already exists. This is done with new environment variables, and the current default behaviour is left unchanged (no-ops if the table already exists).

2024-01-29 10:11 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault?pullRequest=25115)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault?pullRequest=25115)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**mdiggin** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault?pullRequest=25115).</sub>

2024-02-21 22:21 UTC, schavis requested changes

2024-02-21 22:21 UTC, schavis commented on website/content/docs/configuration/storage/dynamodb.mdx
> +  also be provided via the environment variable `AWS_DYNAMODB_BILLING_MODE`.
```suggestion
- `billing_mode` `(string: "PROVISIONED")` - Specifies which billing mode should be
  be used for the table. Choices are "PROVISIONED" or "PAY_PER_REQUEST". You can
  also configure billing mode with the `AWS_DYNAMODB_BILLING_MODE` environment variable .
```

Style correction: avoid "this" as a pronoun

2024-02-21 22:21 UTC, schavis commented on website/content/docs/configuration/storage/dynamodb.mdx
> +  `AWS_DYNAMODB_ALLOW_UPDATES`.
```suggestion
- `dynamodb_allow_updates` `(string: "")` - Specifices if the billing mode or the
  read/write capacity or the table should be updated if the provided values differ
  from the existing table. You can also configure updates with the 
  `AWS_DYNAMODB_ALLOW_UPDATES` environment variable.
```

2024-02-21 22:21 UTC, schavis commented on website/content/docs/configuration/storage/dynamodb.mdx
> +  This can also be provided via the environment variable `AWS_DYNAMODB_READ_CAPACITY`.
```suggestion
  You can also set the read capacity with the `AWS_DYNAMODB_READ_CAPACITY` environment variable.
```

2024-02-21 22:21 UTC, schavis commented on website/content/docs/configuration/storage/dynamodb.mdx
> +  This can also be provided via the environment variable `AWS_DYNAMODB_WRITE_CAPACITY`.
```suggestion
  You can also set the write capacity with the `AWS_DYNAMODB_WRITE_CAPACITY` environment variable.
```

2024-02-21 22:21 UTC, schavis commented on website/content/docs/configuration/storage/dynamodb.mdx
> +By default, if a table with the configured name already exists, Vault will not modify it -
```suggestion
By default, Vault will not modify the table if a table with the configured name already exists
```
Style correction: write in active voice

2024-02-22 20:48 UTC, schavis commented
Content LGTM. Feel free to merge once ENG signs off on the code changes

2025-01-20 18:11 UTC, VioletHynes reviewed
Hi there! Sorry it took us some time to get to this PR, but it broadly looks good. I appreciate all of the new tests for the functionality. There's some small changes I'd like to see before it gets merged, e.g. the typo in the changelog. Thank you for this contribution, and I'm eager to try and see this one to merge.

2025-01-20 18:11 UTC, VioletHynes commented on website/content/docs/configuration/storage/dynamodb.mdx
> +  read/write capacity or the table should be updated if the provided values differ
```suggestion
  read/write capacity of the table should be updated if the provided values differ
```

2025-01-20 18:11 UTC, VioletHynes commented on changelog/25115.txt
> +physical/dynamodb: Allow Vault to modify it's DynamoDB table and use per-per-request billing mode.
```suggestion
physical/dynamodb: Allow Vault to modify its DynamoDB table and use per-per-request billing mode.
```

2025-01-20 18:11 UTC, VioletHynes commented on changelog/25115.txt
> +physical/dynamodb: Allow Vault to modify it's DynamoDB table and use per-per-request billing mode.
"it's" means "it is", "its" is the possessive form of it

2025-01-20 18:11 UTC, VioletHynes commented on physical/dynamodb/dynamodb_test.go
> +		t.Fatalf("err: %s", err)
Instead of this, we should prefer:
```
	if err != nil {
		t.Fatal(err)
	}
```
or, even better:
```
	require.NoError(t, err)
```

2025-01-20 18:11 UTC, VioletHynes commented on physical/dynamodb/dynamodb_test.go
> +		t.Fatalf("err: %s", err)
I've only left this comment once, but this applies for every `t.Fatalf` where we're only adding `err`. Please fix it in each instance.

2025-01-20 18:11 UTC, VioletHynes commented on physical/dynamodb/dynamodb_test.go
> +func TestDynamoDBBackendUpdateReadWriteCapacity(t *testing.T) {
Please add a godoc for all new tests :)

2025-01-20 18:11 UTC, VioletHynes commented on physical/dynamodb/dynamodb_test.go
> +	if newBillingMode != "PAY_PER_REQUEST" {
nit: prefer
```
require.Equal(t, "PAY_PER_REQUEST", newBillingMode)
```

2025-01-20 20:38 UTC, michael-diggin commented on physical/dynamodb/dynamodb_test.go
> +		t.Fatalf("err: %s", err)
Done.

2025-01-20 20:41 UTC, VioletHynes approved these changes
Thank you! This looks great. Again, apologies it took us a while to get eyes on this. Appreciate your patience. 

I'll wait for CI to finish on this PR and I need to get the 'requested changes' unflagged so it can be merged, but I'll try and get this merged as soon as everything's green.

2025-01-20 20:43 UTC, michael-diggin commented
> Hi there! Sorry it took us some time to get to this PR, but it broadly looks good. I appreciate all of the new tests for the functionality. There's some small changes I'd like to see before it gets merged, e.g. the typo in the changelog. Thank you for this contribution, and I'm eager to try and see this one to merge.

No problem and thanks for the review! I've updated the PR based on your comments. There's a small annoying issue where some of my earlier commits had the incorrect commit author which the CLA check doesn't like.

2025-01-20 21:13 UTC, michael-diggin commented
Ah I've made a mess of this - let me close it and create a new one to save a huge headache, sorry!

2025-01-20 21:13 UTC, closed without merging

2025-01-20 21:17 UTC, VioletHynes commented
Hehe, it seems so! No matter, feel free to tag me (and @schavis) in the next one you open and I'll re-review.