Docs: Policy Syntax page to include UI details.
hashicorp/vault pull request #25449
Opened 2024-02-15 18:03 UTC by aphorise

New section to include details of builtin UI related portions.

<img width="1100" alt="Screenshot 2024-02-15 at 18 58 18" src="https://github.com/hashicorp/vault/assets/974854/ef93dc5f-a54f-4380-9467-0dd84c246338">

2024-02-15 18:13 UTC, jasonodonnell commented on website/content/docs/concepts/policies.mdx
> +and using the `default` policy the following paths are automatically included:
```suggestion
The Vault UI may require different ACL capabilities compared to the CLI. When [enabled](/vault/docs/configuration/ui#activating-the-vault-ui) 
and using the `default` policy the following paths are automatically included:
```

2024-02-16 21:12 UTC, schavis requested changes

2024-02-16 21:12 UTC, schavis commented on website/content/docs/concepts/policies.mdx
> +inaccessible then you may observe related warning or error messages within the UI itself.
```suggestion
Vault uses the [/sys/internal/ui/resultant-acl](/vault/api-docs/system/internal-ui-resultant-acl)
endpoint to repackage information used by the UI. If you do not have have
permission to call the `ui/resultant-acl` endpoint, you may receive warnings or
errors in the UI.
```

I'm not sure I actually understood what this block was trying to say, so may edits may not be entirely accurate.

2024-02-16 21:12 UTC, schavis commented on website/content/docs/concepts/policies.mdx
> +capability will have no effect.
```suggestion
```

Moved to the beginning of the section

2024-02-16 21:12 UTC, schavis commented on website/content/docs/concepts/policies.mdx
> +been granted path capabilities on.
```suggestion
<Note title="The ui/mounts endpoint is unauthenticated"> 

  Vault uses the endpoint for UI and CLI preflight checks and is intended for
  internal use only. Requests that include an `X-Vault-Token` will return
  all mounts the token has path capabilities on.

</Note>
```

2024-02-28 22:59 UTC, yhyakuna commented
@schavis  I created a [Jira task](https://hashicorp.atlassian.net/browse/SPE-742). Let's convert this into a partial and also ad this to the UI docs.

2024-03-14 18:22 UTC, schavis commented
[PR 25956](https://github.com/hashicorp/vault/pull/25956) to add the UI policy info as a partial is in review

2024-03-22 22:36 UTC, schavis requested changes

2024-03-22 22:36 UTC, schavis commented on website/content/docs/concepts/policies.mdx
> +</Note>
```suggestion
## UI policy requirements

@include 'ui/policy-requirements.mdx'
```

Updated to use the new partial

2024-03-25 22:42 UTC, schavis approved these changes

2024-03-25 22:45 UTC, merged