Add documentation for new Identity Token `.well-known` endpoint used for Plugin WIF
hashicorp/vault pull request #25469
Opened 2024-02-15 22:31 UTC by vinay-gopalan

Adds documentation for the endpoint added to Vault in #24898.

2024-02-16 17:04 UTC, austingebauer approved these changes
Thanks @vinay-gopalan

2024-02-16 17:04 UTC, austingebauer commented on website/content/api-docs/secret/identity/tokens.mdx
> +  "issuer": "https://example.com/v1/identity/oidc",
Thanks!

2024-02-16 17:04 UTC, austingebauer commented on website/content/api-docs/secret/identity/tokens.mdx
> +  "issuer": "https://example.com/v1/identity/oidc",
```suggestion
  "issuer": "https://example.com/v1/identity/oidc/plugins",
```

2024-02-16 20:40 UTC, schavis requested changes

2024-02-16 20:40 UTC, schavis commented on website/content/api-docs/secret/identity/tokens.mdx
> +Query this path to retrieve a set of claims about the plugin identity tokens' configuration. The response is a compliant [OpenID Provider Configuration Response](https://openid.net/specs/openid-conne
```suggestion
Use the token endpoint to retrieve an
[OpenID Provider Configuration Response](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse)
with claims about the identity token configuration for a plugin.
```

Style correction: write in active voice

2024-02-16 21:18 UTC, vinay-gopalan commented on website/content/api-docs/secret/identity/tokens.mdx
> +Query this path to retrieve a set of claims about the plugin identity tokens' configuration. The response is a compliant [OpenID Provider Configuration Response](https://openid.net/specs/openid-conne
Updated, thanks!

2024-02-21 17:15 UTC, vinay-gopalan commented
@schavis I have made the changes that you had requested. Could you give the PR another review whenever you get the chance, thanks! 🙏🏼

2024-02-21 23:42 UTC, schavis approved these changes

2024-02-22 17:09 UTC, merged