Document known issue to release notes and upgrade guide for 1.16.0
hashicorp/vault pull request #25540
Opened 2024-02-20 22:06 UTC by marcboudreau

When upgrading a Vault server to version 1.16.0, the Vault UI will no longer be able to display the version because it is now using a different endpoint. To account for this, the **default** policy has been updated to allow access to this endpoint, but the change is not applied to an existing **default** policy. This note serves to inform the users that they need to make a small change to the **default** policy to allow the Vault UI to retrieve the version.

2024-02-21 21:07 UTC, schavis requested changes

2024-02-21 21:07 UTC, schavis commented on website/content/partials/known-issues/1_16-default-policy-needs-to-be-updated.mdx
> +the Vault server version and display it to the users.
```suggestion
```

Folded into the previous edit/suggestion

2024-02-22 11:25 UTC, tomhjp commented
@schavis @marcboudreau I also have some documentation I would like to add to the upgrading to 1.16 page but it's going to cause a lot of conflicts if I try to land it before this PR. Please could we either expedite this PR or split out the creation of the page from the specific content getting added to the page?

2024-02-22 17:43 UTC, marcboudreau commented on website/content/partials/known-issues/1_16-default-policy-needs-to-be-updated.mdx
> +- 1.16.0
Good point, will fix.

2024-02-22 17:48 UTC, marcboudreau commented
@tomhjp I'm going to try and get this merged ASAP.

2024-02-22 20:45 UTC, schavis approved these changes

2024-02-22 20:45 UTC, merged