Docs: New plugins pinned versions APIs
hashicorp/vault pull request #25604
Opened 2024-02-23 14:01 UTC by tomhjp

Docs for the new plugin version pinning API.

2024-02-23 19:38 UTC, thyton approved these changes
LGMT

2024-02-27 20:07 UTC, schavis requested changes

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  URL.
```suggestion
- `type` `(string: <required>)` – Path parameter specifying the target plugin
  type for the pinned version. May be "auth", "database", or "secret".
```

Style correction: write in active voice

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  pinned version for. This is part of the request URL.
```suggestion
- `name` `(string: <required>)` – Path parameter specifying the plugin name for
  the pinned version.
```

Style correction : write in active voice

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  to pin. Cannot be a builtin version, and must already exist in the catalog.
```suggestion
- `version` `(string: <required>)` - Specifies the semantic version of the plugin
  to pin. Cannot be a builtin version and must already exist in the catalog.
```

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +This endpoint reads the pinned version for a plugin with the given type and name.
```suggestion
Read the pinned version for a plugin with the given type and name.
```

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  "database", or "secret". This is part of the request URL.
```suggestion
- `type` `(string: <required>)` – Path parameter specifying the target plugin
  type for the pinned version. May be "auth", "database", or "secret".
```

Edited to use similar language as the other endpoints

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  part of the request URL.
```suggestion
- `name` `(string: <required>)` – Path parameter specifying the plugin name for
  the pinned version.
```

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +This endpoint deletes any pinned version for a plugin with the given type and name.
```suggestion
Delete any pinned version for a plugin with the given type and name.
```

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  "database", or "secret". This is part of the request URL.
```suggestion
- `type` `(string: <required>)` – Path parameter specifying the target plugin
  type for the pinned version. May be "auth", "database", or "secret".
```

2024-02-27 20:07 UTC, schavis commented on website/content/api-docs/system/plugins-pins.mdx
> +  part of the request URL.
```suggestion
- `name` `(string: <required>)` – Path parameter specifying the plugin name for
  the pinned version.
```

2024-03-06 16:33 UTC, yhyakuna approved these changes
LGTM

2024-03-08 01:38 UTC, schavis approved these changes

2024-03-08 12:48 UTC, merged

2024-03-08 12:48 UTC, tomhjp commented
Thanks!