[DOCS] Edits to audit filtering overview
hashicorp/vault pull request #25676
Opened 2024-02-27 20:58 UTC by schavis

2024-02-28 10:00 UTC, peteski22 requested changes
Thanks for this Sarah 😄 

I added some suggestions and fixes in-line.

Also, two things:

1. I think we should consider moving the '`filter` properties for audit devices' section above 'Fallback auditing devices'
2. It doesn't look like we call out that you can only ever enable a single fallback device which is quite important

2024-03-06 18:50 UTC, mister-ken approved these changes
lgtm

2024-03-06 19:30 UTC, schavis commented
@peteski22 

> 1. I think we should consider moving the '`filter` properties for audit devices' section above 'Fallback auditing devices'

The reason I put the fallback auditing devices first is because we have properties that refer to setting the fallback. Fully explaining the feature first makes the parameters easier to understand.

> 2. It doesn't look like we call out that you can only ever enable a single fallback device which is quite important
Technically you can have multiple fallbacks if you just create an audit device that doesn't use filtering, no? But I see your point about clarifying that you can only explicitly label one device as an official fallback. Besides the special metrics, what's the advantage of having an explicit fallback rather than just an unfiltered audit device?

2024-03-06 19:41 UTC, schavis commented on website/content/docs/concepts/filtering/audit.mdx
> +`path`        | `path == auth/approle/login`        | Log all activity against the AppRole login path
We should use whichever notation will make readers most successful when they inevitably copy/paste the examples. Does that means adding `\"` to all our examples? (I'm not super familiar with the nuances of JSON pointer notation)

2024-03-06 20:09 UTC, peteski22 commented
> 2\. Technically you can have multiple fallbacks if you just create an audit device that doesn't use filtering, no?

No, only a single fallback device can be enabled (using the `fallback=true` option). The fallback is the one device that Vault explicitly will try if you're only using filters and none match.

2024-03-06 20:55 UTC, peteski22 requested changes

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +audit file, `vault-audit.log` continues to capture all audit events.
There are 4 entries as there's a request and a response for each action (sorry).

```suggestion
The `/var/kv-audit.log` now includes four entries in total: a request and response
entry for the command that enabled `my-kv` and another request and response entry
for the command that wrote a secret to `my-kv`. Entries for the other commands
are captured by the fallback device. And the original audit file, `vault-audit.log`
continues to capture all audit events.
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +  ```
`fallback` has to come at the end where the kv config options go.

```suggestion
  ```shell-session
  vault audit enable                \
    -path=my-fallback               \
    -description="fallback device"  \
    file                            \
    fallback=true                   \
    file_path=/tmp/kv-audit.fallback.log
  ```
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +  ```
I swapped the last two options around so they both end with the `file_path` (and escaped the `kv`).

```suggestion
  ```shell-session
  vault audit enable                \
    -path kv-only                   \
    file                            \
    filter="mount_type == \"kv\""   \
    file_path=/logs/kv-audit.log
  ```
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +    vault kv put my-kv my_secret=always_angry
For `kv-v2` the syntax is slightly different (sorry).

```suggestion
    vault kv put -mount=my-kv my_secret the_value=always_angry
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +  But the root namespace is technically unnamed and only matches to an empty
```suggestion
  Non-root namespace paths **must** end with a trailing slash (`/`) to match correctly.
  But the root namespace does not have a path and only matches to an empty
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +for `(N > 10)`would exclude audit entires where `(N == 10)`, which may not be
```suggestion
for `(N > 10)`would exclude audit entries where `(N == 10)`, which may not be
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +The fallback audit device saves all audit entires that would otherwise get
```suggestion
The fallback audit device saves all audit entries that would otherwise get
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +`path`        | `path == auth/approle/login`        | Log all activity against the AppRole login path
We should encourage users to escape quote the values (I think you've mentioned this in a comment already to make life easier when folks copy/paste).

```suggestion
`mount_point` | `mount_point == \"auth/oidc\"`          | Log all entries for the `auth/oidc` mount point
`mount_type`  | `mount_type == \"kv-v2\"`           | Log all entries from `kv-v2` plugins
`namespace`   | `namespace != \"admin/\"`               | Log all entries **not** in the admin namespace
`operation`   | `operation == \"read\"`                 | Log all read operations
`path`        | `path == \"auth/approle/login\"`        | Log all activity against the AppRole login path
```

2024-03-06 20:55 UTC, peteski22 commented on website/content/docs/concepts/filtering/audit.mdx
> +  `namespace != \"\"` matches any audit entry **not** in the root namespace.
```suggestion
  `namespace != \"\"` matches any audited request **not** in the root namespace.
```

2024-03-06 21:19 UTC, schavis commented
> No, only a single fallback device can be enabled (using the `fallback=true` option). The fallback is the one device that Vault explicitly will try if you're only using filters and none match.

I know you can only explicitly name a single device with `fallback=true`, I meant that *functionally* if you have an audit device with no filters enabled, it captures *everything* and acts as an informal backup because you technically still write everything to it, even things that would have been dropped by the filter. 

What I'm trying to tease apart is why folks benefit from having an *explicit* fallback (labeled as such with the `fallback` parameter) rather than just having a secondary device that captures everything "just in case".

2024-03-07 09:21 UTC, peteski22 approved these changes

2024-03-07 09:21 UTC, merged