docs/vault-k8s injector: update for v1.4.0 release
hashicorp/vault pull request #25790
Opened 2024-03-06 00:03 UTC by tvoran

https://github.com/hashicorp/vault-k8s/releases/tag/v1.4.0

2024-03-06 19:55 UTC, schavis requested changes

2024-03-06 19:55 UTC, schavis commented on website/content/docs/platform/k8s/injector/annotations.mdx
> +  for more details.
```suggestion
  for a particular Vault host. The connection limit includes all connections in the dialing,
  active, and idle states. See [Vault Agent Template Config](/vault/docs/agent-and-proxy/agent/template#global-configurations)
  for more details.
```

2024-03-07 13:46 UTC, tomhjp approved these changes
LGTM 👍

2024-03-08 01:33 UTC, schavis approved these changes

2024-03-08 06:03 UTC, tvoran commented
Thanks!

2024-03-08 06:03 UTC, merged