Peteski22/userpass/prehashed passwords
hashicorp/vault pull request #25862
Opened 2024-03-11 11:20 UTC by peteski22

Fixes: https://github.com/hashicorp/vault/issues/3069 (Allow a pre-hashed password to be given when creating a userpass user).

Brought this PR in via the front door, the potted history involves an inactive contributor that didn't sign the CLA back in 2018, someone trying to bring it back from the dead, and a sustaining rotation.

Code could be simplified if the [API supported hash validation](https://github.com/golang/go/issues/20896).

Ideally would have a @hashicorp/vault-crypto person review just to make sure we're not doing something silly.

**Further information**:

* https://en.wikipedia.org/wiki/Bcrypt#Versioning_history
* https://auth0.com/blog/hashing-in-action-understanding-bcrypt/

Co-authored by @Ivan-Roger

2024-03-11 19:50 UTC, schavis requested changes

2024-03-11 19:50 UTC, schavis commented on website/content/docs/auth/userpass.mdx
> +  necessary.
```suggestion

The result is a new user, "mitchellh", with the password "foo", who is 
associated with the "admins" policy. 
```

Style correction: avoid "this" as a pronoun.

2024-03-11 19:50 UTC, schavis commented on website/content/docs/auth/userpass.mdx
> +  This enables the userpass auth method at `auth/userpass`. To enable it at a different path, use the `-path` flag:
Suggest simplifying the instructions by adding this to the text before the example command as:

Enable the userpass auth method at the default `auth/userpass` path. You can choose to enable the auth method at a different path with the `-path` flag:

2024-03-12 17:49 UTC, kubawi commented on builtin/credential/userpass/path_user_password_test.go
> +
```suggestion
```

2024-03-12 17:58 UTC, sgmiller approved these changes

2024-03-12 17:59 UTC, schavis approved these changes

2024-03-12 18:16 UTC, merged