vault-24597: add key types and key creation for CMAC
hashicorp/vault pull request #25967
Opened 2024-03-15 15:00 UTC by rculpepper

2024-03-15 16:04 UTC, stevendpclark reviewed
This looks great! One small comment.

2024-03-15 16:04 UTC, stevendpclark commented on sdk/helper/keysutil/policy.go
>  		if p.Type == KeyType_AES128_GCM96 {
I believe we are missing KeyType_AES128_CMAC here, so both CMAC key types will be 256 bit?

2024-03-15 16:04 UTC, stevendpclark commented on builtin/logical/transit/path_keys_test.go
> +func TestTransit_CreateKey(t *testing.T) {
Love it!

2024-03-15 16:13 UTC, sgmiller requested changes
Echoing Steve's comment about not understanding key sizes (forgot the spec on this), and one comment but otherwise lgtm

2024-03-18 17:04 UTC, stevendpclark approved these changes
👍

2024-04-10 18:20 UTC, sgmiller approved these changes

2024-04-19 14:39 UTC, merged