[DOCS] Updating approle docs and token partial to include batch token prefer…
hashicorp/vault pull request #26490
Opened 2024-04-18 08:03 UTC by JMGoldsmith

This updates the text around using batch tokens for approle authentication methods and mentions to use the batch type token when using machine auth in the partial that is used in other places.

2024-04-18 14:03 UTC, brianshumate commented on website/content/partials/tokenstorefields.mdx
> +  time. If using machine based authentication it is recommended to use `batch`
```suggestion
  time. For machine based authentication cases, you should use `batch` 
```

2024-04-18 17:11 UTC, schavis requested changes

2024-04-18 17:11 UTC, schavis commented on website/content/docs/auth/approle.mdx
> +for human operators. You should use `batch` tokens with this auth method as a recommended best practice.
```suggestion
for human operators. We recommend using `batch` tokens with the
 `AppRole` auth method.
```
Style correction: avoid "this" as a pronoun, especially across sentences

2024-04-19 07:11 UTC, JMGoldsmith commented
> @JMGoldsmith Make sure to add the appropriate backport labels before merging if you want the updates published to the current docs (e.g., backport/1.16.x, backport/1.15.x, and backport/1.14.x)

Done!

2024-04-19 16:32 UTC, brianshumate approved these changes

2024-04-19 16:32 UTC, merged