Update tcp.mdx
hashicorp/vault pull request #26601
Opened 2024-04-23 17:40 UTC by bpaxton-hashi

per customer request in support ticket #141025 I've updated the description of tls_disable_client_certs to provide clarification.

2024-04-30 18:48 UTC, schavis requested changes

2024-04-30 18:48 UTC, schavis commented on website/content/docs/configuration/listener/tcp.mdx
> +  is for Vault to request client (authentication) certificates when available.
```suggestion
  is for Vault to request client authentication certificates when available.
```
I don't think the parenthesis are necessary here

2024-05-02 20:01 UTC, schavis approved these changes

2024-05-03 17:32 UTC, mladlow commented
Closing in favor of https://github.com/hashicorp/vault/pull/26816 (which has a corrected GitHub account)

2024-05-03 17:32 UTC, closed without merging