Added exclusion draft docs
hashicorp/vault pull request #26696
Opened 2024-04-30 17:01 UTC by peteski22

2024-05-22 23:19 UTC, schavis requested changes

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +* `entity_id` from requests where the `/auth/client_token` in the entry matches `hmac` and then more than one other character.
```suggestion
Use multiple JSON blocks to exclude:

* `data` from both the request and response when the mount type is `transit`.
* `entity_id` from requests where the `/auth/client_token` starts with `hmac`
  followed by at least one other character.
```

It's worth clarifying if `\"hmac.+\" only matches to strings that *start* with "hmac" or any string that contains "hmac" with at least one character after it. I'm assuming the former in the edit, but feel free to adjust the suggestion if it's the latter.

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +each of these entries contain different objects such as `auth`, `request` and `response`.
```suggestion
To accurately construct `condition` and `fields`, Vault operators need a solid
understanding of their audit entry structures. At a high level, there are only
**request** audit entries and **response** audit entries, but each of these
entries can contain different objects such as `auth`, `request` and `response`.

We strongly encourage operaters to review existing audit logs from a timeframe
of at least 2-4 weeks to better identify appropriate exclusion conditions and
fields.
```

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +JSON examples which refer to `<auth>` are referring to this object.
```suggestion
The following auth object definition includes example data with simple types
(`string`, `bool`, `int`) and used in other JSON examples that include an
`<auth>` object.
```
Style correction: avoid "this" as a pronoun

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +JSON examples which refer to `<request>` are referring to this object.
```suggestion
The following request object definition includes example data with simple types
(`string`, `bool`, `int`) and used in other JSON examples that include an
`<request>` object.
```

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +JSON examples which refer to `<response>` are referring to this object.
```suggestion
The following response object definition includes example data with simple types
(`string`, `bool`, `int`) and used in other JSON examples that include an
`<response>` object.
```

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +The JSON schema for both request and response audit entries are included below.
```suggestion
```

I don't think the section heading is helping here. I'd recommend removing it and bumping the request/response sections to `h2` so they show in the TOC

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +### Request audit entry schema
```suggestion
## Request audit entry schema
```

2024-05-22 23:19 UTC, schavis commented on website/content/docs/enterprise/audit/exclusion.mdx
> +### Response audit entry schema
```suggestion
## Response audit entry schema
```

2024-05-22 23:19 UTC, schavis commented on website/content/partials/audit-options-common.mdx
> +section of the auditing overview for more information.
```suggestion
- `exclude` `(string: "")` - <EnterpriseAlert inline="true" /> Defines a set of 
  rules such that, when the condition is matched, Vault removes the specified
  fields from the audit entry before writing to the audit log. Refer to the
  [exclusion](/vault/docs/enterprise/audit/exclusion) section of the auditing
  overview for more information.
```
Style correction: write in active voice

2024-05-23 10:18 UTC, peteski22 commented on website/content/docs/enterprise/audit/exclusion.mdx
> +your auditing process.
@schavis would this be acceptable? 

```suggestion
particular fields in an audit entry that is written to a particular audit log, and fine-tune
your auditing process.
```

2024-06-03 19:03 UTC, schavis approved these changes

2024-06-05 21:48 UTC, vishalnayak commented on website/content/docs/enterprise/audit/exclusion.mdx
> +Once you enable an audit device with exclusions, every audit entry Vault sends to
`every audit entry Vault` might take paraphrasing a little bit for easy reading.

2024-06-05 21:50 UTC, vishalnayak approved these changes

2024-06-11 07:39 UTC, merged