PKI: Change sign-intermediate to truncate notAfter by default (behavior change)
hashicorp/vault pull request #26796
Opened 2024-05-02 19:50 UTC by stevendpclark

- The PKI sign-intermediate API allowed an end-user to request a TTL value that would extend beyond the signing issuer's notAfter. This would generate an invalid CA chain when properly validated.
 - We are now changing the default behavior to truncate the returned certificate to the signing issuer's notAfter.
 - End-users can get the old behavior by configuring the signing issuer's leaf_not_after_behavior field to permit, and call sign-intermediary with the new argument enforce_leaf_not_after_behavior to true. The new argument could also be used to enforce an error instead of truncating behavior if the signing issuer's leaf_not_after_behavior is set to err.

2024-05-08 02:50 UTC, schavis requested changes

2024-05-08 02:50 UTC, schavis commented on website/content/api-docs/secret/pki.mdx
> +   to go beyond.
```suggestion
By default, Vault truncates the `notAfter` field of the signed intermediary
to use the `notAfter` field of the signing issuer, it the computed field for the
intermediary goes beyond the prescribed length.
```
The docs are versioned, so calling out the version isn't necessary and making the text an aside doesn't necessarily add meaningful context, so we can just make the information part of the document.

2024-05-08 02:50 UTC, schavis commented on website/content/docs/upgrading/upgrade-to-1.17.x.mdx
> +the signing issuer's notAfter if calculated to be greater.
```suggestion
Prior to 1.17.x, Vault allowed the calculated sign-intermediate `notAfter` field
to go beyond the signing issuer `notAfter` field. The extended value lead to a
CA chain that would not validate properly. As of 1.17.x, Vault truncates the
intermediary `notAfter` value to the signing issuer `notAfter` if the calculated
field is greater.
```

Style correction: write in active voice

2024-05-08 02:50 UTC, schavis commented on website/content/docs/upgrading/upgrade-to-1.17.x.mdx
> +will along with setting the `enforce_leaf_not_after_behavior` to true will restore the legacy behavior.
```suggestion
You can use the new `enforce_leaf_not_after_behavior` flag on the
sign-intermediate API along with the `leaf_not_after_behavior` flag for the
signing issuer to opt out of the truncating behavior.

When you set `enforce_leaf_not_after_behavior` to true, the sign-intermediate
API uses the `leaf_not_after_behavior` value configured for the signing issuer
to control truncation the behavior. Setting the issuer `leaf_not_after_behavior`
field to `permit` and `enforce_leaf_not_after_behavior` to true restores the
legacy behavior.
```

Style correction: write in active voice

2024-05-09 15:18 UTC, victorr approved these changes
👍

2024-05-09 15:22 UTC, merged