docs/auth/jwt: add resolved version in upgrade guide
hashicorp/vault pull request #27015
Opened 2024-05-14 14:58 UTC by fairclothjm

2024-05-14 17:46 UTC, schavis requested changes

2024-05-14 17:46 UTC, schavis commented on website/content/partials/known-issues/1_16-jwt_auth_config.mdx
> +This issue was resolved in `1.16.2`.
```suggestion
<Note title="Resolved">
   Resolved in Vault v1.16.2
</Note>
```

Suggest making the resolved note more eye-catching

2024-05-15 15:22 UTC, fairclothjm commented
@schavis Thanks, the requested changes have been resolved.

2024-05-16 15:03 UTC, mladlow reviewed
Would you mind making this consistent with how we've added other resolutions? I haven't seen us add a separate note-style block before.

I believe for consistency we'd add to line 10 something like "This issue is addressed in Vault 1.16.2 and later" or something along those lines.

2024-05-16 16:40 UTC, fairclothjm commented
Thanks @mladlow I would be happy to make the change. @schavis suggested the note-styling and I would not want to override their suggestion without approval.

2024-05-16 16:42 UTC, fairclothjm commented
@mladlow addressed in https://github.com/hashicorp/vault/pull/27015/commits/2bef5b8ef73bd84ac514da7290dcd2b62e14a0bb

2024-05-17 15:06 UTC, mladlow approved these changes
@schavis I've gone ahead and approved this because I think it takes into account your feedback as well, and I want to unblock @fairclothjm from merging.

2024-05-17 15:59 UTC, fairclothjm commented
Merging is blocked. I believe I require approval from @schavis since they request changes.

2024-05-22 15:09 UTC, fairclothjm commented
@schavis Hello, I am unable to merge this until I get your approval since you requested changes. Thanks!

2024-05-23 21:13 UTC, merged