agent: allow changing file ownership in file sink
hashicorp/vault pull request #27123
Opened 2024-05-18 18:06 UTC by clwluvw

Allow changing the ownership of the token file in file sink.

2024-05-23 19:30 UTC, schavis requested changes

2024-05-23 19:30 UTC, schavis commented on website/content/docs/agent-and-proxy/autoauth/sinks/file.mdx
> +- `mode` `(int: optional)` - A string containing an octal number representing the bit pattern for the file mode, similar to chmod. Note: This configuration option is only available in Vault 1.3.0 and
```suggestion
- `mode` `(int: optional)` - Octal number string representing the bit pattern for the file mode, similar to `chmod`.
```

The Vault docs only go back to v1.4, so I'm not sure the callout is necessary

2024-05-27 17:12 UTC, VioletHynes commented on website/content/docs/agent-and-proxy/autoauth/sinks/file.mdx
> +- `group` `(int: optional)` - The GID to use for token file. Defaults to the current group id.
```suggestion
- `group` `(int: optional)` - The GID to use for token file. Defaults to the current group ID.
```

2024-05-27 17:12 UTC, VioletHynes approved these changes
Hey there! This looks great, thank you for this.

I'm going to add a changelog and try and get this merged shortly.

2024-05-27 17:17 UTC, VioletHynes commented on changelog/27123.txt
> +
```suggestion
```
```

2024-05-27 17:17 UTC, VioletHynes commented on changelog/27123.txt
> +
```suggestion
```
```

2024-05-27 19:33 UTC, VioletHynes commented
Hi there @clwluvw ! Just one little thing before we get this merged:

the linter check failed with the following:
`command/agentproxyshared/sink/file/file_sink_test.go:139:1: Test TestFileSinkMode_Ownership is missing a go doc`

Could you make sure to add a godoc for the test, describing what it does and what it's for? Thanks :D

I also need to run this by @schavis to make sure there are no outstanding requested changes.

2024-05-27 19:36 UTC, clwluvw commented
Hi @VioletHynes - Thanks for the review. I just added the godoc for the test.

2024-05-27 19:47 UTC, VioletHynes commented
Thanks! It's a holiday in some parts of the world today and I'll need to confirm with Sarah before I merge this, but I hope to get this merged soon this week :)

2024-05-30 19:11 UTC, schavis approved these changes

2024-05-30 19:11 UTC, merged