Docs: VAULT_DISABLE_REDIRECTS added further clarity
hashicorp/vault pull request #27256
Opened 2024-05-29 11:47 UTC by aphorise

Added limit to HTTP redirects - where the current text does not explicitly call out that only a single redirect will be followed.

2024-06-03 19:29 UTC, schavis requested changes

2024-06-03 19:29 UTC, schavis commented on website/content/docs/commands/index.mdx
> +Prevents the Vault client from following HTTP redirects. By default, the Vault CLI client will only follow a single redirect and any additional redirection can result in an empty or unexpected respon
```suggestion
Prevents the Vault client from following HTTP redirects. By default, the
Vault CLI client only follows the first redirect. Additional redirects can
result in an empty or unexpected response. 
```
Style correction: write in active voice

2024-06-05 04:32 UTC, schavis approved these changes

2024-06-05 04:33 UTC, schavis commented
@aphorise Please add the appropriate backport labels if you want to publish the change for 1.16 or 1.17

2024-06-06 09:46 UTC, aphorise commented
> @aphorise Please add the appropriate backport labels if you want to publish the change for 1.16 or 1.17

Added backports to as far back as possible (1.13). Thanks very much.

2024-06-28 18:53 UTC, merged