docs: note vle is not supported with aws snapstart
hashicorp/vault pull request #27329
Opened 2024-06-03 16:45 UTC by fairclothjm

2024-06-03 17:29 UTC, Zlaticanin approved these changes

2024-06-03 17:31 UTC, vinay-gopalan approved these changes

2024-06-03 19:26 UTC, schavis requested changes
Tweaked to use tag-style aside

2024-06-03 19:26 UTC, schavis commented on website/content/docs/platform/aws/lambda-extension.mdx
> +
```suggestion
<Note title="Not SnapStart compatible">

  The Vault Lambda extension does not currently  work with
  [AWS SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html).

</Note>

```

2024-06-04 13:59 UTC, fairclothjm commented
@schavis Hello, I have made the requested changes. Could you please re-review 🙏 . Thanks!

2024-06-05 04:31 UTC, schavis approved these changes

2024-06-05 04:31 UTC, merged