Edit alias_name_source explanation
hashicorp/vault pull request #27382
Opened 2024-06-06 14:25 UTC by mladlow

We wanted to clarify the difference between the two options and the implications.

I need to see how this renders because I'm not sure the line breaks will work.

2024-06-11 02:20 UTC, schavis requested changes

2024-06-11 02:20 UTC, schavis commented on website/content/api-docs/auth/kubernetes.mdx
> +  use `serviceaccount_name` where the risks of this are mitigated or acceptable given your use case.
```suggestion
  When you specify `serviceaccount_uid`, Vault uses a machine generated UID from
  the service account as the identity alias name. Using a service account UID is
  both the default and the recommended method as it the more secure option.

  When you specify `serviceaccount_name`, Vault uses the name and namespace from
  the service account as the identity alias name (e.g., `vault/vault-auth`). You
  should only use `serviceaccount_name` if you consider the risk acceptable or
  can mitigate the risk with strong controls around the creation/deletion/access
  of your Kubernetes service accounts and need one of the following capabilities:

    1. fine-grained control over the mapping between Kubernetes service accounts
      and Vault identities.
    1. a simpler process for setting entity aliases before creating Kubernetes
      service account creation.
```

Style correction: write in active voice, make key information easier to scan

2024-07-09 18:06 UTC, mladlow commented
@schavis could you take another look at this please?

2024-08-06 23:50 UTC, schavis approved these changes

2024-08-06 23:50 UTC, schavis commented
Apologies, I've been a bit underwater. Feel free to merge!

2024-08-07 23:07 UTC, merged