[docs] document manual entity merge failures when sent to PR secondary cluster
hashicorp/vault pull request #28013
Opened 2024-08-07 16:58 UTC by elliesterner

### Description
Documents a known issue with manual entity merge requests getting sent to the PR secondary cluster. 

### TODO only if you're a HashiCorp employee
- [ ] **Labels:** If this PR is the CE portion of an ENT change, and that ENT change is
  getting backported to N-2, use the new style `backport/ent/x.x.x+ent` labels
  instead of the old style `backport/x.x.x` labels.
- [ ] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
  the normal `backport/x.x.x` label (there should be only 1).
- [ ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [ ] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [ ] **RFC:** If this change has an associated RFC, please link it in the description.
- [ ] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

2024-08-07 20:57 UTC, schavis requested changes

2024-08-07 20:57 UTC, schavis commented on website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
> +- All Enterprise versions from 0.7.0 up
```suggestion

- Vault Enterprise v0.7.0+
```

2024-08-07 20:57 UTC, schavis commented on website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
> +and will be reflected only temporarily on the PR secondary's active node.
```suggestion
If you send a manual entity merge to a PR secondary cluster, the change is
temporarily reflected on the active node of the PR secondary cluster, but Vault
does not save the change to persistent storage. 
```

Style correction: write in active voice

2024-08-07 20:57 UTC, schavis commented on website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
> +All manual entity merge requests should be sent to the primary cluster.
```suggestion

Always send manual entity merge requests to the primary cluster.
```

2024-08-08 19:01 UTC, ltcarbonell approved these changes

2024-08-08 19:12 UTC, davidadeleon approved these changes

2024-08-08 20:31 UTC, schavis approved these changes

2024-08-08 20:32 UTC, merged