Docs (lambda-extension): add warning about caching re. distributed tracing headers
hashicorp/vault pull request #28118
Opened 2024-08-19 04:08 UTC by aztalbot

### Description
- adds warning in the caching section of the vault—lambda-extension docs
- explains how distributed tracing headers can produce unintended consequences on caching
- if this behavior changes in a future version of the vault-extension (see open [PR](https://github.com/hashicorp/vault-lambda-extension/pull/145)), a warning like this may still be useful for usage of older versions

2024-08-20 23:19 UTC, schavis requested changes

2024-08-20 23:19 UTC, schavis commented on website/content/docs/platform/aws/lambda-extension.mdx
> +unique and prevent cache hits.
```suggestion
<Warning title="Distributed tracing headers may negate the cache">

  The Vault Lambda Extension cache key includes headers from proxy requests. As
  a result, distributed tracing headers like `traceparent` can lead to
  individualized hashes that make repeated requests appear unique and cause cache
  misses.

</Warning>
```

Style correction: write in active voice, avoid possessives, use tag-style aside notation

2024-08-21 00:07 UTC, schavis approved these changes

2024-08-27 17:14 UTC, yhyakuna approved these changes

2024-08-27 17:15 UTC, merged