VAULT: 21710 - prevent duplicate audit file_path targets
hashicorp/vault pull request #28751
Opened 2024-10-22 17:43 UTC by tvo0813

### Description
Preventing duplicate audit file_path

### TODO only if you're a HashiCorp employee
- [ ] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
  to N, N-1, and N-2, using the `backport/ent/x.x.x+ent` labels. If this PR is in the CE repo, you should only backport to N, using the `backport/x.x.x` label, not the enterprise labels.
    - [ ] If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use **all** available enterprise labels.
- [ ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [ ] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [ ] **RFC:** If this change has an associated RFC, please link it in the description.
- [ ] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

2024-10-23 13:52 UTC, ltcarbonell requested changes
Could you add a sample of the new error response from Vault to the description? This will help us see how Vault responds without needing to run it manually.

2024-10-23 16:28 UTC, tvo0813 commented
Tested locally and is working as it should (failed when enabling same file_path)
```tin.vo@tin command % APATH=vaduit1.json;                                                 
tin.vo@tin command % vault audit enable -path=file1 file file_path=${APATH};             
Success! Enabled the file audit device at: file1/
tin.vo@tin command % vault audit enable -path=file2 file log_raw=true file_path=${APATH};
Error enabling audit device: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/audit/file2
Code: 400. Errors:

* file_path already in use: invalid configuration```

2024-10-24 11:21 UTC, kubawi approved these changes
LGTM, thanks Tin! 

I am leaving an approval and some suggestions to make comments clearer. I also left a comment on the Jira for this task, please hold off with merging until the discussion there is finished.

2024-10-24 11:21 UTC, kubawi commented on changelog/28751.txt
> +audit: Prevent the audit process from allowing duplicate file path targets
```suggestion
audit: Prevent users from enabling multiple audit devices of file type with the same file_path to write to.
```

2024-10-24 11:21 UTC, kubawi commented on vault/audit_test.go
> +// specifically checking for duplicate file paths in audit options across multiple paths.
```suggestion
// TestCore_EnableExistingAudit ensures that we don't allow enabling a file audit device
// with the same `file_path` as one of the existing ones.
```

2024-10-24 17:14 UTC, ltcarbonell approved these changes

2024-10-24 17:54 UTC, merged