[DOCS] Update the PKI secrets engine docs title & description
hashicorp/vault pull request #29136
Opened 2024-12-10 02:01 UTC by yhyakuna

### Description

This PR updates the secrets engine docs title & description for style consistency, as well as SEO improvement.

- Match the H1 header and the `page_title` for consistency
- Use `<Note>` callout elment instead of `~>`

### TODO only if you're a HashiCorp employee
- [x] **Backport Labels:** If this fix needs to be backported, use the appropriate `backport/` label that matches the desired release branch. Note that in the CE repo, the latest release branch will look like `backport/x.x.x`, but older release branches will be `backport/ent/x.x.x+ent`.
    - [ ] **LTS**: If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use **all** available enterprise labels.
- [ ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [ ] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [ ] **RFC:** If this change has an associated RFC, please link it in the description.
- [ ] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

2024-12-10 13:36 UTC, jonathanfrappier commented on website/content/docs/secrets/pki/index.mdx
> +description: Dynamically generate X.509 certificate with the PKI secrets engine plugin.
`a certificate` or `certificates`? 
```suggestion
description: Dynamically generate X.509 certificates with the PKI secrets engine plugin.
```

2024-12-10 13:39 UTC, jonathanfrappier approved these changes

2024-12-10 18:40 UTC, jonathanfrappier approved these changes

2024-12-16 13:49 UTC, victorr requested changes
I left a couple of suggestions but I am "requesting changes" as the description in file `rotation-primitives.mdx` needs a slight correction.

2024-12-16 13:49 UTC, victorr commented on website/content/docs/secrets/pki/considerations.mdx
> +   Understand the important considerations and guidance before using the PKI secrets engine to generate the CA certificates.
Suggestion: change to "generate certificates", or even just change to end with "...before using the PKI secrets engine"

2024-12-16 13:49 UTC, victorr commented on website/content/docs/secrets/pki/est.mdx
> +   Understand the configuration and limitations of Vault's PKI secrets engine implementation of the EST protocol.
Please consider spelling out "Enrollment over Secure Transport" in the description, to match the descriptions of the CIEPS and CMPv2 pages.

2024-12-16 13:49 UTC, victorr commented on website/content/docs/secrets/pki/rotation-primitives.mdx
> +   Understand the X.509 certificate primitive fields when you are using the PKI secrets engine.
I don't think "primitive fields" is correct. Primitives here refer to certificate types, so maybe something along the lines of:
>Understand the primitive certificate types for root and intermediate CA rotation.

2024-12-16 22:55 UTC, yhyakuna commented
@victorr Thank you so much for your help in updating the description! I believe I incorporated all your feedback, and it's ready for your review.

2024-12-17 01:09 UTC, jonathanfrappier approved these changes

2024-12-19 13:36 UTC, victorr approved these changes
Awesome. 👍

2024-12-19 13:36 UTC, merged