docs/vault-k8s: updates for v1.6.0 release
hashicorp/vault pull request #29152
Opened 2024-12-11 19:05 UTC by tvoran

### Description
Updates documentation for the vault agent injector [v1.6.0](https://github.com/hashicorp/vault-k8s/releases/tag/v1.6.0) release.

### TODO only if you're a HashiCorp employee
- [x] **Backport Labels:** If this fix needs to be backported, use the appropriate `backport/` label that matches the desired release branch. Note that in the CE repo, the latest release branch will look like `backport/x.x.x`, but older release branches will be `backport/ent/x.x.x+ent`.
    - [-] **LTS**: If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use **all** available enterprise labels.
- [-] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [x] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [-] **RFC:** If this change has an associated RFC, please link it in the description.
- [-] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

2024-12-11 20:54 UTC, benashz submitted a review, later dismissed

2025-01-06 20:25 UTC, schavis requested changes

2025-01-06 20:25 UTC, schavis commented on website/content/docs/platform/k8s/injector/index.mdx
> +default set of golang metrics):
```suggestion
Vault Agent injector collects the following Prometheus metrics in addition to
the default set of `golang` metrics:
```

Style correction: do not capitalize features, avoid parentheticals

2025-01-06 20:25 UTC, schavis commented on website/content/docs/platform/k8s/injector/index.mdx
> +  the injector's queue.
```suggestion
- `vault_agent_injector_request_queue_length` - The number of pending webhook requests for the injector.
```

"A gauge" doesn't really describe the metric. Is it the total number of pending requests? The average number of queued requests over an interval?

2025-01-06 20:25 UTC, schavis commented on website/content/docs/platform/k8s/injector/index.mdx
> +  where `injection_type` is `init_only`, `sidecar_only`, or `init_and_sidecar`.
```suggestion
- `vault_agent_injector_injections_by_namespace_total` - The total count of
  Agent container injections, grouped by Kubernetes `namespace` and `injection_type`.
  Vault Agent counts the following injection types:
    - `init_only`
    - `sidecar_only`
    - `init_and_sidecar`.
```

Style correction: one idea per sentence

2025-01-06 20:25 UTC, schavis commented on website/content/docs/platform/k8s/injector/index.mdx
> +  of failed Agent Sidecar injections by Kubernetes `namespace`.
```suggestion
  of failed Agent Sidecar injections, grouped by Kubernetes `namespace`.
```

2025-01-06 20:25 UTC, schavis commented on website/content/docs/platform/k8s/injector/index.mdx
> +true`](/vault/docs/platform/k8s/helm/configuration#metrics) in the Helm chart.
```suggestion
```
Suggest moving this to the start of the section so folks can find it easier/faster.

2025-01-06 20:25 UTC, schavis commented on website/content/docs/platform/k8s/injector/index.mdx
> +
```suggestion

<Tip>

Set [`injector.metrics.enabled`](/vault/docs/platform/k8s/helm/configuration#metrics) 
to `true` in the Helm chart to start collecting injector metrics.

</Tip>
```

2025-01-08 06:28 UTC, tvoran commented on website/content/docs/platform/k8s/injector/index.mdx
> +  the injector's queue.
Sure, "number of pending webhook requests" is clearer.

2025-01-08 23:43 UTC, yhyakuna approved these changes

2025-01-10 01:36 UTC, schavis approved these changes

2025-01-10 04:54 UTC, merged