UI - Added default text description where none are set for builtin secret engines. Resolves: #7304
hashicorp/vault pull request #9814
Opened 2020-08-24 22:46 UTC by aphorise

@meirish - I'd appreciate your input on this as well as a few other UI related PR's that are pending; thank you in advance.

![Screenshot 2020-08-25 at 00 41 30](https://user-images.githubusercontent.com/974854/91103647-4a8f8e80-e66c-11ea-9663-ca4c6f3ebadb.png)

2021-02-17 20:10 UTC, chelshaw requested changes
A couple pointers to help clean this up (and get tests passing). A test that checks for the both the default and custom-set description to show up would be great too!

2021-02-17 20:10 UTC, chelshaw commented on ui/app/templates/vault/cluster/secrets/backends.hbs
> +              {{#if (eq "ad" backend.type)}}Active Directory credentials & service accounts.{{/if}}
We should store these strings somewhere centralized (such as `options-for-backend`) and then get them here instead of doing all these if statements

2021-02-17 20:10 UTC, chelshaw commented on ui/app/templates/vault/cluster/secrets/backends.hbs
> +          <font class="has-text-grey is-size-8" style="margin-left:10px;">
Getting linter errors that `style` on templates (hbs files) is not allowed, so we should instead use a class for the left margin (can add to `helpers.scss` and follow the pattern there)

2021-02-17 20:10 UTC, chelshaw commented on ui/app/templates/vault/cluster/secrets/backends.hbs
> +              {{#if (eq "ad" backend.type)}}Active Directory credentials & service accounts.{{/if}}
Save each string as `description` key to its corresponding engine type in `SECRET_BACKENDS` and then use the helper like 
```hbs
{{#unless backend.description}}
  {{get (options-for-backend backend.type) "description"}}
{{else}} ...
```

2021-08-04 22:23 UTC, aphorise commented
Redundant and likely addressed in #11995 already.

2021-08-04 22:23 UTC, closed without merging